#include "item_list.hpp"
#include "region.hpp"
#include "hints.hpp"
#include "hint_list.hpp"
#include "logic.hpp"
#include "item_category.hpp"
#include "../code/include/z3D/z3Ditem.h"
#include <array>

using namespace Logic;

static std::array<Item, KEY_ENUM_MAX> itemTable;

void ItemTable_Init() {   
    //Item(0, 0, "test", "test", regiion, hint, 0, Misc, test, );
    /*itemTable[EXAMPLE] =                         Item( StartingItemAddress,  Starting Item Index, {English name     				         French          					  Spanish},                            Location Name,           Region,             HintKey,               GetItemIndexValue,Item Category,      Location Category,);*/
    itemTable[NONE] =                              Item(0,                      0,                  Text{"No Item",                         "Rien",                             "Sin Objeto"},                        "No Item",               Misc,               NONE,                  0,                None,              None,          );

    itemTable[KOKIRI_SWORD]                      = Item(0,                      0,                  Text{ "Kokiri Sword",                   "Épée Kokiri",                     "Espada Kokiri" },                     "Misc.",                 Misc,               KOKIRI_SWORD,          0x37,            MainInventory,      StartingItems, );
	itemTable[RAZOR_SWORD]                       = Item(0,                      0,                  Text{"Razor Sword",				     "Lame Rasoir",						"Espada Afilada"},                        "Mountain Smith Day 1",  MountainVillage,    RAZOR_SWORD,           0x38,            MainInventory,      NpcRewards,    );
    itemTable[GILDED_SWORD]                      = Item(0,                      0,                  Text{"Gilded Sword",                    "Lame Doree",                      "Espada de Esmeril"},                  "Mountain Smith Day 2",  MountainVillage,    GILDED_SWORD,          0x39,            MainInventory,      NpcRewards,    );
    itemTable[GREAT_FAIRYS_SWORD]                = Item(0x776364,               0x10,               Text{"Great Fairys Sword",              "Grande Épée de Fees",              "Espada de la Gran Hada"},            "Ikana Great Fairy",     IkanaCanyon,        GREAT_FAIRYS_SWORD,    0x130,           MainInventory,      NpcRewards,    );
    itemTable[HEROS_SHIELD]                      = Item(0x??,                   0x10,               Text{"Heros Shield",                    "Bouclier du Heros",                "Escudo del Heroe"},                  "Starting Hero Shield",  Misc.,              HEROS_SHIELD,          0x129,           Shields,            StartingItems, );
    itemTable[MIRROR_SHIELD]                     = Item(0x??,                   0,                  Text{"Mirror Shield",                   "Bouclier miroir",                  "Escudo espejo"},                      "Mirror Shield",        BeneathTheWell,     MIRROR_SHIELD,         0x33,            MainInventory,      Chests,        );
    itemTable[DEKU_STICK]                        = Item(0x77635C,               0x08,               Text{"Deku Stick,"                      "Bâton Mojo"                        "palos deku" },                        "Deku Stick",           WestClockTown,      DEKU_STICK,            0xBE,            DekuSticks,         Purchases,     );
    itemTable[LAND_TITLE]                        = Item(0,                      0,                  Text{"Land Title Deed",				    "Titre de propriete fonciere",      "Escritura de propiedad de la Tierra" },"Clock Town Scrub Trade",SouthClockTown,   LAND_TITLE,            0x97,            TradeItems,         NpcRewards,    );
    itemTable[SWAMP_TITLE]                       = Item(0,                      0,                  Text{"Swamp Title Deed",				"Titre de propriete des marais",	"Escriture de propiedad del pantano" }, "Swamp Scrub Trade",   SouthernSwamp,      SWAMP_TITLE,           0x98,            TradeItems,         NpcRewards,    );
    itemTable[MOUNTAIN_TITLE]                    = Item(0,                      0,                  Text{"Mountain Title Deed",			    "Titre de propriete de la montagne","Escitura de propiedad de la montana" },"Mountain Scrub Trade",GoronVillage,       MOUNTAIN_TITLE,        0x99,            TradeItems,         NpcRewards,    );
    itemTable[OCEAN_TITLE]                       = Item(0,                      0,                  Text{"Ocean Title Deed",				"Titre de propriete de l'ocean",	"Escitura de propiedad del oceano" },   "Ocean Scrub Trade",   ZoraHall,           OCEAN_TITLE,           0x9A,            TradeItems,         NpcRewards,    );
    itemTable[BOMBERS_NOTEBOOK]                  = Item(0,                      0,                  Text{"Bomber's Notebook",				"Carnet de bombardier",				"Cuaderno de bombardero" },             "Bombers' Hide and Seek", NorthClockTown,  BOMBERS_NOTEBOOK,      0x50,            MainInventory,      NpcRewards,    );
    itemTable[ROOM_KEY]                          = Item(0,                      0,                  Text{"Room Key",						"Clef de chambre",					"Llave del cuarto" },                   "Inn Reservation",      StockPotInn,       ROOM_KEY,              0xA0,            TradeItems,         NpcRewards,    );
    itemTable[LETTER_KAFEI]                      = Item(0,                      0,                  Text{"Letter to Kafei",				    "Lettre a Kafei",					"Carta a Kafei" },                      "Midnight Meeting",    StockPotInn,        LETTER_KAFEI,          0xAA,            TradeItems,         NpcRewards,    );
    itemTable[PENDANT_MEMORIES]                  = Item(0,                      0,                  Text{"Pendant of Memories",			    "Pendentif de Souvenirs",			"Colgante de recuerdos" },              "Kafei",               LaundryPool,        PENDANT_MEMORIES,      0xAB,            TradeItems,         NpcRewards,    );
    itemTable[LETTER_MAMA]                       = Item(0,                      0,                  Text{"Special Delivery to Mama",		"Livraison speciale a maman",		"Entrega especial a mama" },            "Curiosity Shop Man #2", LaundryPool,      LETTER_MAMA,           0xA1,            TradeItems,         NpcRewards,    );
    itemTable[MOONS_TEAR]                        = Item(0,                      0,                  Text{"Moon's Tear",					    "Larme de lune",					"Lagrima de luna" },                    "Astronomy Telescope",   TerminaField,     MOONS_TEAR,            0x96,            TradeItems,         Events,        );
    itemTable[SPIN_ATTACK]                       = Item(0,                      0x9C,               Text{"Spin Attack",					    "attaque de rotation",				"ataque giratorio" },                   "Woodfall Great Fairy",  Woodfall,         SPIN_ATTACK,           0x12D,           MagicPowers,        NpcRewards,    );
    itemTable[LENS_OF_TRUTH]                     = Item(0x776362,               0x0E,               Text{"Lens of Truth",                   "Loupe de vérité",                  "Lupa de la Verdad"},                   "Lens of Truth Chest", GoronVillage,       LENS_OF_TRUTH,         0x42,            MainInventory,      Chests,        );
    itemTable[FIRE_ARROWS]                       = Item(0x776356,               0X02,               Text{"Fire Arrow",                      "Flèche de feu",                    "Flecha de fuego"},                     "Fire Arrow Chest",    SnowheadTemple,     FIRE_ARROWS,           0x25,            MainInventory,      BossFights,    );
    itemTable[ICE_ARROWS]                        = Item(0x776357,               0x03,               Text{"Ice Arrow",                       "Flèche de glace",                  "Flecha de hielo"},                     "Ice Arrow Chest",     GreatBayTemple,     ICE_ARROWS,            0x26,            MainInventory,      BossFights,    );
    itemTable[LIGHT_ARROWS]                      = Item(0x776358,               0x04,               Text{"Light Arrow",                     "Flèche de lumière",                "Flecha de luz"},                       "Light Arrow Chest,"   StoneTowerTemple,   LIGHT_ARROWS,          0x27,            MainInventory,      BossFights,    );
    itemTable[HOOKSHOT]                          = Item(0x776363,               0x0F,               Text{ "Hookshot",						"Grappin",							"Gancho" },								"Hookshot Chest",      PiratesFortressInterior, HOOKSHOT,         0x41,            MainInventory,      Chests,        );
	itemTable[MAGIC_BEAN]                        = Item(0x77635E,               0x0A,               Text{"Magic Bean",                      "Haricot magique",                  "Habichuelas mágicas"},                 "Bean Man",            DekuPalace,         MAGIC_BEAN,            0x11E,           MainInventory,      Purchases,     );
    //itemTable[MAGIC_BEAN_PACK]                   = Item(Text{"Magic Bean Pack",                 "Paquet de haricots magiques",      "Lote de habichuelas mágicas"},             ITEMTYPE_ITEM,  0xC9,                  true,       &MagicBeanPack,        MAGIC_BEAN_PACK);
    itemTable[DOUBLE_DEFENSE]                    = Item(0x775320,               0x01,               Text{"Double Defense",                  "Double défence",                   "Doble poder defensivo"},               "Ocean Great Fairy",    ZoraCape,          DOUBLE_DEFENSE,        0x12F,           MagicPowers,        NpcRewards,    );
	//itemTable[OCARINA_OF_TIME]                   = Item(Text{"Ocarina of Time",                 "Ocarina du temps",                 "Ocarina del Tiempo"},                      ITEMTYPE_ITEM, 	GI_OCARINA_OF_TIME,    true,  	   &OcarinaOfTime,        OCARINA_OF_TIME,			false,);
    itemTable[PICTOBOX]                          = Item(0x776361,               0x0D,               Text{"Pictograph Box",                  "Boite a Images",                   "Camara Pictografica"},                 "Koume",                SouthernSwamp,     PICTOGRAPH_BOX,        0x43,            MainInventory,       NpcRewards,   );
    itemTable[POWDER_KEG]                        = Item(0,                      0x0C,               Text{"Powder Keg",                      "Baril de Poudre",                  "Barril de Polovora"},                  "Powder Keg Challenge", GoronVillage,      POWDER_KEG,            0x123,           MainInventory,       NpcRewards,   );
    itemTable[KEATON_MASK]                       = Item(0x775372,               0x3A,               Text{"Keaton Mask",                     "Masque de Keaton",                 "Careta de Keaton"},                    "Curiosity Shop Man #1",LaundryPool,       KEATON_MASK,           0x80,            Masks,               NpcRewards,   );
    itemTable[BUNNY_HOOD]                        = Item(0x775374,               0x39,               Text{"Bunny Hood",                      "Masque du lapin",                  "Capucha de conejo"},                   "Guru Guru"             RomaniRanch,       BUNNY_HOOD,            0x7F,            Masks,               NpcRewards,   );
    itemTable[GORON_MASK]                        = Item(0x775377,               0x33,               Text{"Goron Mask",                      "Masque Goron",                     "Máscara Goron"},                       "Darmani",              MountainVillage,   GORON_MASK,            0x79,            Masks,               NpcRewards,   );
    itemTable[ZORA_MASK]                         = Item(0x77537D,               0x34,               Text{"Zora Mask",                       "Masque Zora",                      "Máscara Zora"},                        "Mikau",                GreaBayCoast,      ZORA_MASK,             0x7A,            Masks,               NpcRewards,   );
    itemTable[DEKU_MASK]                         = Item(0x775371,               0x32,               Text{"Deku Mask",                       "Masque Mojo",                      "Máscara Deku"},                        "Starting Item",        Misc,              DEKU_MASK,             0x78,            Masks,               StartingItems,);
    itemTable[POSTMANS_HAT]                      = Item(0x77536C,               0x3E,               Text{"Postman's Mask",                  "Chapeau de facteur",               "Sombrero de cartero"},                 "Postmans' Freedom Reward", EastClockTown, POSTMANS_HAT,          0x84,            Masks,               NpcRewards,   );
    itemTable[ALL_NIGHT_MASK]                    = Item(0x77536D,               0x38,               Text{"All-Night Mask",                  "Masque de nuit",                   "Máscara toda la noche"},               "All-Night Mask Purchase",  WestClockTown, ALL_NIGHT_MASK,        0x7E,            Masks,               NpcRewards,   );
    itemTable[BLAST_MASK]                        = Item(0x77536E,               0x47,               Text{"Blast Mask",                      "Masque anti-explosion",            "Máscara explosiva"},                   "Old Lady",                 NorthClockTown, BLAST_MASK,           0x8D,            Makks,               NpcRewards,   );
    itemTable[STONE_MASK]                        = Item(0x77536F,               0x45,               Text{"Stone Mask",                      "Masque de pierre",                 "Máscara de piedra"},                   "Invisible Soldier",        RoadToIkana,   STONE_MASK,            0x8B,            Masks,               NpcRewards,   );
    itemTable[GREAT_FAIRYS_MASK]                 = Item(0x775370,               0x40,               Text{"Great Fairy's Mask",              "Masque de grande fee",             "Máscara de gran hada"},                "Town Great Fairy",       NorthClockTown,  GREAT_FAIRYS_MASK,     0x131,           Masks,               NpcRewards,   );
    itemTable[BREMEN_MASK]                       = Item(0x775373,               0x46,               Text{"Bremen Mask",                     "Masque de Breme",                  "Máscara de Bremen"},                   "Guru Guru",              LaundryPool,     BREMEN_MASK,           0x8C,            Masks,               NpcRewards,   );
    itemTable[DON_GEROS_MASK]                    = Item(0x775375,               0x42,               Text{"Don Gero's Mask",                 "Masque de Don Gero",               "Máscara de Don Gero"},                 "Hungry Goron",           MountainVillage, DON_GEROS_MASK,        0x88,            Masks,               NpcRewards,   );
    itemTable[MASK_OF_SCENTS]                    = Item(Text{"Mask of Scents",                  "Masque des Senteurs",              "Máscara de aromas"},                       ITEMTYPE_ITEM,  GI_MASK_SCENTS,        true,       &ScentsMask,           MASK_OF_SCENTS,			false,);
    itemTable[ROMANIS_MASK]                      = Item(Text{"Romani's Mask",                   "Masque de Romani",                 "Máscara de Romani"},                       ITEMTYPE_ITEM,  GI_MASK_ROMANI,        true,       &RomaniMask,           ROMANIS_MASK,				false,);
    itemTable[CIRCUS_LEADERS_MASK]               = Item(Text{"Circus Leader's Mask",            "Masque de chef de cirque",         "Máscara de lider de circo"},               ITEMTYPE_ITEM,  GI_MASK_CIRCUS,        true,       &CircusMask,           CIRCUS_LEADERS_MASK,		false,);
    itemTable[KAFEIS_MASK]                       = Item(Text{"Kafei's Mask",                    "Masque de Kafei",                  "Máscara de Kafei"},                        ITEMTYPE_ITEM,  GI_MASK_KAFEI,         true,       &KafeiMask,            KAFEIS_MASK,				false,);
    itemTable[COUPLES_MASK]                      = Item(Text{"Couple's Mask",                   "Masque de couple",                 "Máscara de pareja"},                       ITEMTYPE_ITEM,  GI_MASK_COUPLE,        true,       &CoupleMask,           COUPLES_MASK,				false,);
    itemTable[KAMAROS_MASK]                      = Item(Text{"Kamaro's Mask",                   "Masque de Kamaro",                 "Máscara de Kamaro"},                       ITEMTYPE_ITEM,  GI_MASK_KAMARO,        true,       &KamaroMask,           KAMAROS_MASK,				false,);
    itemTable[GIBDOS_MASK]                       = Item(Text{"Gibdo's Mask",                    "Masque Gibdo",                     "Máscara de Gibdo"},                        ITEMTYPE_ITEM,  GI_MASK_GIBDO,         true,       &GibdoMask,            GIBDOS_MASK,				false,);
    itemTable[GAROS_MASK]                        = Item(Text{"Garo's Mask",                     "Masque de Garo",                   "Máscara de Garo"},                         ITEMTYPE_ITEM,  GI_MASK_GARO,          true,       &GaroMask,             GAROS_MASK,				false,);
    itemTable[CAPTAINS_HAT]                      = Item(Text{"Captain's Hat",                   "Chapeau de capitaine",             "Sombrero de Capitan"},                     ITEMTYPE_ITEM,  GI_MASK_CAPTAIN,       true,       &CaptainHat,           CAPTAINS_HAT,				false,);
    itemTable[GIANTS_MASK]                       = Item(Text{"Giant's Mask",                    "Masque de geant",                  "Máscara de gigante"},                      ITEMTYPE_ITEM,  GI_MASK_GIANT,         true,       &GiantsMask,           GIANTS_MASK,				false,);
    itemTable[FIERCE_DIETY_MASK]                 = Item(Text{"Fierce Diety Mask",               "Masque Dietetique Fiere",          "Máscara Fiere Diety"},                     ITEMTYPE_ITEM,  GI_MASK_FIERCE,        true,       &FierceMask,           FIERCE_DIETY_MASK,		false,);
    itemTable[MASK_OF_TRUTH]                     = Item(Text{"Mask of Truth",                   "Masque de vérité",                 "Máscara de la Verdad"},                    ITEMTYPE_ITEM,  GI_MASK_MASK,          true,       &MaskofTruth,          MASK_OF_TRUTH,			false,);
//
    itemTable[SWAMP_SKULLTULA_TOKEN]             = Item(Text{"Swamp Skulltula Token",           "Jeton de Skulltula dorée",         "Símbolo de skulltula dorada"},             ITEMTYPE_SWAMP_TOKEN,     GI_SWAMP_TOKEN,       true,   &SwampSkulltulaTokens,     SWAMP_SKULLTULA_TOKEN,		    false,);
	itemTable[OCEANSIDE_SKULLTULA_TOKEN]         = Item(Text{"Oceanside Skulltula Token",       "Jeton de Skulltula dorée",         "Símbolo de skulltula dorada"},             ITEMTYPE_OCEANSIDE_TOKEN, GI_OCEANSIDE_TOKEN,   true,   &OceansideSkulltulaTokens, OCEANSIDE_SKULLTULA_TOKEN,	    false,);
	
	itemTable[CT_STRAY_FAIRY]					 = Item(Text{"Clock Town Stray Fairy",			"Fee errante de la Bourg-Clocher",	"Cuidad Reloj Hada Callejera"},				ITEMTYPE_ITEM,	GI_CT_SF,	          true,		   &ClockStray,	          CT_STRAY_FAIRY,				false,);
	itemTable[WF_STRAY_FAIRY]					 = Item(Text{"Woodfall Stray Fairy",			"Fee errante de la Bois-Cascade",	"Hada Callejera del Bosque  Catarata"},		ITEMTYPE_ITEM,	GI_WF_SF,	          true,	       &WoodfallStrays,	      WF_STRAY_FAIRY,				false,);
	itemTable[SH_STRAY_FAIRY]					 = Item(Text{"Snowhead Stray Fairy",			"Fee errante de la Pic des Neiges",	"Hada Callejera del Pico Nevado"},			ITEMTYPE_ITEM,	GI_SH_SF,             true,  	   &SnowheadStrays,	      SH_STRAY_FAIRY,				false,);
	itemTable[GBT_STRAY_FAIRY]					 = Item(Text{"Great Bay Stray Fairy",			"Fee errante de la Grande Baie",	"Gran Hada Callejera de la Bahia"},			ITEMTYPE_ITEM,	GI_GBT_SF,	          true,		   &GreatBayStrays,	      GBT_STRAY_FAIRY,				false,);
	itemTable[ST_STRAY_FAIRY]					 = Item(Text{"Stone Tower Stray Fairy",			"Fee errante de la Forteresse de Pierre","Hada Callejera de la Torre Piedra"},  ITEMTYPE_ITEM,	GI_ST_SF,	          true,		   &StoneTowerStrays,	  ST_STRAY_FAIRY,				false,);
		

    //Progression Items
    itemTable[PROGRESSIVE_SWORD]                 = Item(Text{ "Progressive Sword",				"Lame (prog.)",						"Espada progresivo" },						ITEMTYPE_ITEM,     0x80,              true,        &ProgressiveSword,       PROGRESSIVE_SWORD,          false, );
    itemTable[PROGRESSIVE_BOMB_BAG]              = Item(Text{"Progressive Bomb Bag",            "Sac de bombes (prog.)",            "Saco de bombas progresivo"},               ITEMTYPE_ITEM,     0x82,              true,        &ProgressiveBombBag,     PROGRESSIVE_BOMB_BAG,		false,);
    itemTable[PROGRESSIVE_BOW]                   = Item(Text{"Progressive Bow",                 "Arc (prog.)",                      "Arco progresivo"},                         ITEMTYPE_ITEM,     0x83,              true,        &ProgressiveBow,         PROGRESSIVE_BOW,			false,);
    itemTable[PROGRESSIVE_WALLET]                = Item(Text{"Progressive Wallet",              "Bourse (prog.)",                   "Bolsa de rupias progresiva"},              ITEMTYPE_ITEM,     0x85,              true,        &ProgressiveWallet,      PROGRESSIVE_WALLET,			false,);
  //  itemTable[PROGRESSIVE_NUT_UPGRADE]           = Item(Text{"Progressive Nut Capacity",        "Capacité de noix (prog.)",         "Capacidad de nueces deku progresiva"},     ITEMTYPE_ITEM,     0x87,              false,      &noVariable,             PROGRESSIVE_NUT_UPGRADE,     false,);
  //  itemTable[PROGRESSIVE_STICK_UPGRADE]         = Item(Text{"Progressive Stick Capacity",      "Capacité de bâtons (prog.)",       "Capacidad de palos deku progresiva"},      ITEMTYPE_ITEM,     0x88,              false,       &noVariable,            PROGRESSIVE_STICK_UPGRADE,   false,);
    itemTable[PROGRESSIVE_BOMBCHUS]              = Item(Text{"Progressive Bombchu",             "Bombchus (prog.)",                 "Bombchus progresivos"},                    ITEMTYPE_ITEM,     0x89,              true,        &Bombchus,               PROGRESSIVE_BOMBCHUS,		false,);
    itemTable[PROGRESSIVE_MAGIC_METER]           = Item(Text{"Progressive Magic Meter",         "Jauge de magie (prog.)",           "Poder mágico progresivo"},                 ITEMTYPE_ITEM,     0x8A,              true,        &ProgressiveMagic,       PROGRESSIVE_MAGIC_METER,	false,);

    //Bottles
    itemTable[EMPTY_BOTTLE]                      = Item(Text{"Empty Bottle",                    "Flacon vide",                      "Botella vacía"},                           ITEMTYPE_ITEM,     0x0F,              true,        &HasBottle,              EMPTY_BOTTLE,				false,);
    itemTable[BOTTLE_WITH_MILK]                  = Item(Text{"Bottle with Milk",                "Flacon de lait",                   "Botella de leche Lon Lon"},                ITEMTYPE_ITEM,     0x14,              true,        &HasBottle,              BOTTLE_WITH_MILK,			true,);
    itemTable[BOTTLE_WITH_RED_POTION]            = Item(Text{"Bottle with Red Potion",          "Flacon de potion rouge",           "Botella de poción roja"},                  ITEMTYPE_ITEM,     0x8C,              true,        &HasBottle,              BOTTLE_WITH_RED_POTION,		true,);
    itemTable[BOTTLE_WITH_GREEN_POTION]          = Item(Text{"Bottle with Green Potion",        "Flacon de potion verte",           "Botella de poción verde"},                 ITEMTYPE_ITEM,     0x8D,              true,        &HasBottle,              BOTTLE_WITH_GREEN_POTION,	true,);
    itemTable[BOTTLE_WITH_BLUE_POTION]           = Item(Text{"Bottle with Blue Potion",         "Flacon de potion bleue",           "Botella de poción azul"},                  ITEMTYPE_ITEM,     0x8E,              true,        &HasBottle,              BOTTLE_WITH_BLUE_POTION,	true,);
    itemTable[BOTTLE_WITH_FAIRY]                 = Item(Text{"Bottle with Fairy",               "Flacon avec une fée",              "Hada en una botella"},                     ITEMTYPE_ITEM,     0x8F,              true,        &HasBottle,              BOTTLE_WITH_FAIRY,			true,);
    itemTable[BOTTLE_WITH_FISH]                  = Item(Text{"Bottle with Fish",                "Flacon avec un poisson",           "Pez en una botella"},                      ITEMTYPE_ITEM,     0x90,              true,        &HasBottle,              BOTTLE_WITH_FISH,			true,);
    itemTable[CHATEAU_ROMANI]        			 = Item(Text{"Chateau Romani",           		"Chateau Romani",          			"Reserva Romani"},                 			ITEMTYPE_ITEM,  GI_CHATEAU,           true,        &HasBottle,              CHATEAU_ROMANI,				true,);
    itemTable[BOTTLE_WITH_BUGS]                  = Item(Text{"Bottle with Bugs",                "Flacon d'insectes",                "Insecto en una botella"},                  ITEMTYPE_ITEM,     0x92,              true,        &HasBottle,              BOTTLE_WITH_BUGS,			true,);
    itemTable[BOTTLE_WITH_POE]                   = Item(Text{"Bottle with Poe",                 "Flacon avec un Esprit",            "Poe en una botella"},                      ITEMTYPE_ITEM,     0x94,              true,        &HasBottle,              BOTTLE_WITH_POE,			true,);
	itemTable[HOT_SPRING_WATER]                  = Item(Text{"Hot Spring Water",   			    "Eau de Source Chaude",       	    "Agua de Manantial Caliente"},              ITEMTYPE_ITEM,  GI_HOT_SPRING_WATRE,  true,        &HotSpringWater,         HOT_SPRING_WATER,			true,);
    itemTable[SPRING_WATER]                      = Item(Text{"Spring Water",   			        "Eau de Pluie",       	            "Agua de Manantial"},                       ITEMTYPE_ITEM,  GI_SPRING_WATER,      true,        &SpringWater,            SPRING_WATER,				true,);
    
    //Special bottles that can't immediately dump contents
    itemTable[DEKU_PRINCESS]                     = Item(Text{"Deku Princess",   			    "Princesse Mojo",       	        "Princesa Deku"},                           ITEMTYPE_ITEM,  GI_PRINCESS,          true,        &DekuPrincess,           DEKU_PRINCESS,				true,);
    itemTable[BOTTLE_WITH_BIG_POE]               = Item(Text{"Bottle with Big Poe",             "Flacon avec une Âme",              "Gran Poe en una botella"},                 ITEMTYPE_ITEM,     0x93,              true,        &BottleWithBigPoe,       BOTTLE_WITH_BIG_POE,		true,);
	itemTable[GOLD_DUST]  	                     = Item(Text{"Gold Dust",   			  	    "Poudre d'Or",       	      		"Polvo de Oro"},                            ITEMTYPE_ITEM,  GI_GOLD_DUST,         true,        &GoldDust,               GOLD_DUST,			    	true,);
    itemTable[ZORA_EGG]							 = Item(Text{"Zora Egg", 						"Oeuf de Zora",						"Huevo de Zora"},							ITEMTYPE_ITEM, GI_ZORA_EGG,           true,        &ZoraEgg,		    	ZORA_EGG,			    	true,);
	itemTable[SEAHORSE]							 = Item(Text{"Seahorse",						"Hippocampe",						"Caballo de mar"},							ITEMTYPE_ITEM, GI_SEAHORSE,           true,        &Seahorse,	            SEAHORSE,				    true,);
	
    //Songs
    itemTable[SONG_OF_TIME]                      = Item(Text{"Song of Time",                    "Chant du temps",                   "Canción del tiempo"},                      ITEMTYPE_SONG,     0xC5,              true,        &SongOfTime,             SONG_OF_TIME,				false,);
    itemTable[SONG_OF_STORMS]                    = Item(Text{"Song of Storms",                  "Chant des tempêtes",               "Canción de la tormenta"},                  ITEMTYPE_SONG,     0xC6,              true,        &SongOfStorms,           SONG_OF_STORMS,				false,);
    itemTable[SONATA_OF_AWAKENING]               = Item(Text{"Sonata of Awakening",             "Sonate de i'Eveil",                "Sonata del Despertar"},                    ITEMTYPE_SONG,     0xBB,              true,        &SonataOfAwakening,      SONATA_OF_AWAKENING,		false,);
    itemTable[GORONS_LULLABY]                    = Item(Text{"Goron's Lullaby",                 "Berceuse des Gorons",              "Nana Goron"},                       		ITEMTYPE_SONG,     0xBC,              true,        &GoronsLullaby,          GORONS_LULLABY,				false,);
    itemTable[NEW_WAVE_BOSSA_NOVA]               = Item(Text{"New Wave Bossa Nova",             "Bossa Nova des Flots",             "Nueva Bossanova"},                         ITEMTYPE_SONG,     0xBD,              true,        &NewWaveBossaNova,       NEW_WAVE_BOSSA_NOVA,		false,);
    itemTable[ELEGY_OF_EMPTINESS]                = Item(Text{"Elegy of Emptiness",              "Hymne du Vida",                    "Elegia al Vacio"},                         ITEMTYPE_SONG,     0xBE,              true,        &ElegyOfEmptiness,       ELEGY_OF_EMPTINESS,			false,);
    itemTable[OATH_TO_ORDER]               		 = Item(Text{"Oath to Order",             	    "Ode lAppel",       		        "Oda al Order"},   			                ITEMTYPE_SONG,     0xBF,              true,        &OathToOrder, 		    OATH_TO_ORDER,				false,);
    itemTable[EPONAS_SONG]                       = Item(Text{"Epona's Song",                    "Chant d'Épona",                    "Canción de Epona"},                        ITEMTYPE_SONG,     0xC1,              true,        &EponasSong,             EPONAS_SONG,				false,);
    itemTable[INVERTED_SONG_OF_TIME]             = Item(Text{"Inverted Song of Time",           "Chant du Temps Inverse",           "Canción del Tiempo Invertida"},            ITEMTYPE_SONG,     0xC2,              true,        &InvertedSongOfTime,     INVERTED_SONG_OF_TIME,		false,);
    itemTable[SONG_OF_DOUBLE_TIME]               = Item(Text{"Song of Double Time",             "Chant du Temps Accelere",          "Canción del Doble Tiempo"},                ITEMTYPE_SONG,     0xC3,              true,        &SongOfDoubleTime,       SONG_OF_DOUBLE_TIME,		false,);
    itemTable[SONG_OF_HEALING]                   = Item(Text{"Song of Healing",                 "Chant de l'Apaisement",            "Sonata de Curacion"},                      ITEMTYPE_SONG,     0xC4,              true,        &SongOfHealing,          SONG_OF_HEALING,			false,);
    itemTable[SONG_OF_SOARING]                   = Item(Text{"Song of Soaring",                 "Chant de l'Envol",                 "Canción de Vuelo"},                        ITEMTYPE_SONG,     0xC0,              true,        &SongOfSoaring,          SONG_OF_SOARING,			false,);
    
    //Maps and Compasses
    itemTable[WOODFALL_TEMPLE_MAP]               = Item(Text{"Woodfall Temple Map",             "Carte de Temple de Bois-Cascade",  "Mapa del Templo del Bosque Catarata"},     ITEMTYPE_MAP,      0xA5,              false,       &noVariable,             MAP,				        false,);
    itemTable[SNOWHEAD_TEMPLE_MAP]               = Item(Text{"Snowhead Temple Map",             "Carte de Temple du Pic des Neiges","Mapa del Templo del Pico Nevado"},         ITEMTYPE_MAP,      0xA6,              false,       &noVariable,             MAP,				        false,);
    itemTable[GBT_MAP]                           = Item(Text{"Great Bay Temple Map",            "Carte de Temple de la Grande Baie","Mapa del Templo de la Gran Bahia"},        ITEMTYPE_MAP,      0xA7,              false,       &noVariable,             MAP,				        false,);
    itemTable[STONE_TOWER_TEMPLE_MAP]            = Item(Text{"Stone Tower Temple Map",          "Carte du Temple de la Forteresse de Pierre","Mapa del Templo de la Torre de Piedra"},ITEMTYPE_MAP,0xA8,              false,       &noVariable,             MAP,				        false,);
    itemTable[CLOCK_TOWN_MAP]                    = Item(Text{"Clock Town Map",                  "Carte de Bourg-Clocher",           "Mapa de la Cuidad Reloj"},                 ITEMTYPE_MAP,      0xA9,              false,       &noVariable,             MAP,				        false,);
    itemTable[WOODFALL_MAP]                      = Item(Text{"Woodfall Map",                    "Carte du Bois-Cascade",            "Mapa del Bosque Catarata"},                ITEMTYPE_MAP,      0xAA,              false,       &noVariable,             MAP,				        false,);
    itemTable[SNOWHEAD_MAP]                      = Item(Text{"Snowhead Map",                    "Carte du Pic Des Neiges",          "Mapa del Pico Nevado"},                    ITEMTYPE_MAP,      0xAB,              false,       &noVariable,             MAP,				        false,);
    itemTable[GREAT_BAY_MAP]                     = Item(Text{"Great Bay Map",                   "Carte du Plage de la Grande Baie", "Mapa del Costa de la Gran Bahia"},         ITEMTYPE_MAP,      0xAC,              false,       &noVariable,             MAP,				        false,);
    itemTable[STONE_TOWER_MAP]                   = Item(Text{"Stone Tower Map",                 "Carte du Forteresse de Pierre",    "Mapa del Torre de Piedra"},                ITEMTYPE_MAP,      0xAD,              false,       &noVariable,             MAP,				        false,);
    itemTable[ROMANI_RANCH_MAP]                  = Item(Text{"Romani Ranch Map",                "Carte de Ranch Romani",            "Mapa de Rancho Romani"},                   ITEMTYPE_MAP,      0xAE,              false,       &noVariable,             MAP,				        false,);

    itemTable[WOODFALL_TEMPLE_COMPASS]           = Item(Text{"Woodfall Temple Compass",         "Boussole de Temple de Bois-Cascade", "Brújula del Templo del Bosque Catarata"},  ITEMTYPE_COMPASS,  0x9B,            false,       &noVariable,             COMPASS,				    false,);
    itemTable[SNOWHEAD_TEMPLE_COMPASS]           = Item(Text{"Snowhead Temple Compass",         "Boussole de Temple du Pic des Neiges","Brújula del Templo del Pico Nevado"},     ITEMTYPE_COMPASS,  0x9C,            false,       &noVariable,             COMPASS,				    false,);
    itemTable[GBT_COMPASS]                       = Item(Text{"Great Bay Temple Compass",        "Boussole de Temple de la Grande Baie","Brújula del Templo de la Gran Bahia"},    ITEMTYPE_COMPASS,  0x9D,            false,       &noVariable,             COMPASS,				    false,);
    itemTable[STONE_TOWER_TEMPLE_COMPASS]        = Item(Text{"Stone Tower Temple Compass","Boussole du Teple de la Forteresse de Pierre", "Brújula del Templo de la Torre de Piedra"}, ITEMTYPE_COMPASS,  0x9E,       false,       &noVariable,             COMPASS,				    false,);

    //Boss Keys
    itemTable[WOODFALL_TEMPLE_BOSS_KEY]          = Item(Text{"Woodfall Temple Big Key",         "Clé d'or du Temple de Bois-Cascade",   "Gran llave del Templo del Bosque Catarata"}, ITEMTYPE_BOSSKEY,  0x95,         true,        &BossKeyWoodfallTemple,  BOSS_KEY,				    true,);
    itemTable[SNOWHEAD_TEMPLE_BOSS_KEY]          = Item(Text{"Snowhead Temple Big Key",         "Clé d'or du Temple du Pic des Neiges", "Gran llave del Templo del Pico Nevado"},     ITEMTYPE_BOSSKEY,  0x96,         true,        &BossKeySnowheadTemple,  BOSS_KEY,				    true,);
    itemTable[GBT_BOSS_KEY]                      = Item(Text{"Great Bay Temple Big Key",        "Clé d'or du Temple de la Grande Baie", "Gran llave del Templo de la Gran Bahia"},    ITEMTYPE_BOSSKEY,  0x97,         true,        &BossKeyGreatBayTemple,  BOSS_KEY,				    true,);
    itemTable[STONE_TOWER_TEMPLE_BOSS_KEY]       = Item(Text{"Stone Tower Temple Big Key",      "Clé d'or du Temple de la Forteresse de Pierre","Gran llave del Templo de la Torre de Piedra"},ITEMTYPE_BOSSKEY,  0x98,true,       &BossKeyStoneTowerTemple, BOSS_KEY,				    true,);

    //Small Keys
    itemTable[WOODFALL_TEMPLE_SMALL_KEY]         = Item(Text{"Woodfall Temple Small Key",       "Petite clé du Temple de Bois-Cascade", "Llave del Templo del Templo del Bosque Catarata"}, ITEMTYPE_SMALLKEY,0xAF,   true,        &WoodfallTempleKeys,     SMALL_KEY,				    true,);
    itemTable[SNOWHEAD_TEMPLE_SMALL_KEY]         = Item(Text{"Snowhead Temple Small Key",       "Petite clé du Temple du Pic des Neiges",      "Llave del Templo del Pico Nevado"},         ITEMTYPE_SMALLKEY,0xB0,   true,        &SnowheadTempleKeys,     SMALL_KEY,				    true,);
    itemTable[GBT_SMALL_KEY]                     = Item(Text{"Great Bay Temple Small Key",      "Petite clé du Temple de la Grande Baie",    "Llave del Templo del la Gran Bahia"},         ITEMTYPE_SMALLKEY,0xB1,   true,        &GreatBayTempleKeys,     SMALL_KEY,				    true,);
    itemTable[STONE_TOWER_TEMPLE_SMALL_KEY]      = Item(Text{"Stone Tower Temple Small Key",    "Petite clé du Temple de la Forteresse de Pierre","Llave del Templo de la Torre de Piedra"},ITEMTYPE_SMALLKEY,0xB2,   true,        &StoneTowerTempleKeys,   SMALL_KEY,				    true,);

    //Boss Remains
    itemTable[ODOLWAS_REMAINS]                   = Item(Text{"Odolwa's Remains",                "Restes d'Odolwa",                  "Restos de Odolwa"},                        ITEMTYPE_DUNGEONREWARD, 0xCB,         true,        &OdolwasRemains,         ODOLWAS_REMAINS,			false,);
    itemTable[GOHTS_REMAINS]                     = Item(Text{"Goht's Remains",                  "Restes de Rohrk",                  "Restos de Goht"},                          ITEMTYPE_DUNGEONREWARD, 0xCC,         true,        &GohtsRemains,           GOHTS_REMAINS,				false,);
    itemTable[GYORGS_REMAINS]                    = Item(Text{"Gyorg's Remains",                 "Restes de Gyorg",                  "Restos de Gyorg"},                         ITEMTYPE_DUNGEONREWARD, 0xCD,         true,        &GyorgsRemains,          GYORGS_REMAINS,				false,);
    itemTable[TWINMOLDS_REMAINS]                 = Item(Text{"Twinmold's Remains",              "Restes de Skorn",                  "Restos dde Twinmod"},                      ITEMTYPE_DUNGEONREWARD, 0xCE,         true,        &TwinmoldsRemains,       TWINMOLDS_REMAINS,			false,);

    //Generic Items
    itemTable[RECOVERY_HEART]                    = Item(Text{"Recovery Heart",                  "Cœur d'énergie",                   "Corazón"},                                 ITEMTYPE_ITEM,  GI_HEART,             false,       &noVariable,             RECOVERY_HEART,				true,);
    itemTable[GREEN_RUPEE]                       = Item(Text{"Green Rupee",                     "Rubis vert",                       "Rupia verde"},                             ITEMTYPE_ITEM,  GI_RUPEE_GREEN,       false,       &noVariable,             GREEN_RUPEE,				true,);
    itemTable[BLUE_RUPEE]                        = Item(Text{"Blue Rupee",                      "Rubis bleu",                       "Rupia azul"},                              ITEMTYPE_ITEM,  GI_RUPEE_BLUE,        false,       &noVariable,             BLUE_RUPEE,				    true,);
    itemTable[RED_RUPEE]                         = Item(Text{"Red Rupee",                       "Rubis rouge",                      "Rupia roja"},                              ITEMTYPE_ITEM,  GI_RUPEE_RED,         false,       &noVariable,             RED_RUPEE,				    true,);
    itemTable[PURPLE_RUPEE]                      = Item(Text{"Purple Rupee",                    "Rubis pourpre",                    "Rupia morada"},                            ITEMTYPE_ITEM,  GI_RUPEE_PURPLE,      false,       &noVariable,             PURPLE_RUPEE,				true,);
    itemTable[HUGE_RUPEE]                        = Item(Text{"Huge Rupee",                      "Énorme rubis",                     "Rupia gigante"},                           ITEMTYPE_ITEM,  GI_RUPEE_GOLD,        false,       &noVariable,             HUGE_RUPEE,				    true,);
    itemTable[SILVER_RUPEE]                      = Item(Text{"Silver Rupee",                    "rubis d'argent",                   "Rupia de plata"},                          ITEMTYPE_ITEM,  GI_RUPEE_SILVER,      false,       &noVariable,             SILVER_RUPEE,				true,);
    itemTable[PIECE_OF_HEART]                    = Item(Text{"Piece of Heart",                  "Quart de cœur",                    "Pieza de corazón"},                        ITEMTYPE_ITEM,  GI_HEART_PIECE,       false,       &noVariable,             PIECE_OF_HEART,				false,);
    itemTable[HEART_CONTAINER]                   = Item(Text{"Heart Container",                 "Réceptacle de cœur",               "Contenedor de corazón"},                   ITEMTYPE_ITEM,  GI_HEART_CONTAINER_2, false,       &noVariable,             HEART_CONTAINER,			false);
    itemTable[ICE_TRAP]                          = Item(Text{"Ice Trap",                        "Piège de glace",                   "Trampa de hielo"},                         ITEMTYPE_ITEM,  GI_ICE_TRAP,          false,       &noVariable,             ICE_TRAP,				    true,);
    itemTable[MILK]                              = Item(Text{"Milk",                            "Lait",                             "Leche Lon Lon"},                           ITEMTYPE_ITEM,  GI_MILK,              false,       &noVariable,             NONE,				        true,);

    //Refills
    itemTable[BOMBS_5]                           = Item(Text{"Bombs (5)",                       "Bombes (5)",                       "Bombas (5)"},                              ITEMTYPE_REFILL,GI_BOMBS_5,           false,       &noVariable,             BOMBS_5,				    true,);
    itemTable[BOMBS_10]                          = Item(Text{"Bombs (10)",                      "Bombes (10)",                      "Bombas (10)"},                             ITEMTYPE_REFILL,GI_BOMBS_10,          false,       &noVariable,             BOMBS_10,				    true,);
    itemTable[BOMBS_20]                          = Item(Text{"Bombs (20)",                      "Bombes (20)",                      "Bombas (20)"},                             ITEMTYPE_REFILL,GI_BOMBS_20,          false,       &noVariable,             BOMBS_20,				    true,);
    itemTable[BOMBCHU_5]                         = Item(Text{"Bombchu (5)",                     "Bombchus (5)",                     "Bombchus (5)"},                            ITEMTYPE_REFILL,GI_BOMBCHUS_5,        true,        &Bombchus5,              BOMBCHU_5,				    true,);
    itemTable[BOMBCHU_10]                        = Item(Text{"Bombchu (10)",                    "Bombchus (10)",                    "Bombchus (10)"},                           ITEMTYPE_REFILL,GI_BOMBCHUS_10,       true,        &Bombchus10,             BOMBCHU_10,				    true,);
    itemTable[BOMBCHU_20]                        = Item(Text{"Bombchu (20)",                    "Bombchus (20)",                    "Bombchus (20)"},                           ITEMTYPE_REFILL,GI_BOMBCHUS_20,       true,        &Bombchus20,             BOMBCHU_20,				    true,);
    itemTable[BOMBCHU_DROP]                      = Item(Text{"Bombchu Drop",                    "Bombchus",                         "Bombchus"},                                ITEMTYPE_DROP,  GI_BOMBCHUS_10,       true,        &BombchuDrop,            NONE,				        true,);
    itemTable[ARROWS_5]                          = Item(Text{"Arrows (5)",                      "Flèches (5)",                      "Flechas (5)"},                             ITEMTYPE_REFILL,GI_ARROWS_SMALL,      false,       &noVariable,             ARROWS_5,				    true,);
    itemTable[ARROWS_10]                         = Item(Text{"Arrows (10)",                     "Flèches (10)",                     "Flechas (10)"},                            ITEMTYPE_REFILL,GI_ARROWS_MEDIUM,     false,       &noVariable,             ARROWS_10,				    true,);
    itemTable[ARROWS_30]                         = Item(Text{"Arrows (30)",                     "Flèches (30)",                     "Flechas (30)"},                            ITEMTYPE_REFILL,GI_ARROWS_LARGE,      false,       &noVariable,             ARROWS_30,				    true,);
    itemTable[DEKU_NUTS_5]                       = Item(Text{"Deku Nuts (5)",                   "Noix Mojo (5)",                    "Nueces deku (5)"},                         ITEMTYPE_REFILL,GI_NUTS_5,            false,       &noVariable,             DEKU_NUTS_5,				true,);
    itemTable[DEKU_NUTS_10]                      = Item(Text{"Deku Nuts (10)",                  "Noix Mojo (10)",                   "Nueces deku (10)"},                        ITEMTYPE_REFILL,GI_NUTS_10,           false,       &noVariable,             DEKU_NUTS_10,				true,);
    //itemTable[DEKU_SEEDS_30]                     = Item(Text{"Deku Seeds (30)",                 "Graines Mojo (30)",                "Semillas deku (30)"},                      ITEMTYPE_REFILL, GI_SEEDS_30,       false,       &noVariable,             DEKU_SEEDS_30,				true,);
    itemTable[DEKU_STICK_1]                      = Item(Text{"Deku Stick (1)",                  "Bâton Mojo (1)",                   "Palo deku (1)"},                           ITEMTYPE_REFILL,GI_STICKS_1,          false,       &noVariable,             DEKU_STICK_1,				true,);
    itemTable[RED_POTION_REFILL]                 = Item(Text{"Red Potion Refill",               "Potion rouge",                     "Recarga de poción roja"},                  ITEMTYPE_REFILL,GI_POTION_RED,        false,       &noVariable,             NONE,				        true,);
    itemTable[GREEN_POTION_REFILL]               = Item(Text{"Green Potion Refill",             "Potion verte",                     "Recarga de poción verde"},                 ITEMTYPE_REFILL,GI_POTION_GREEN,      false,       &noVariable,             NONE,				        true,);
    itemTable[BLUE_POTION_REFILL]                = Item(Text{"Blue Potion Refill",              "Potion bleue",                     "Recarga de poción azul"},                  ITEMTYPE_REFILL,GI_POTION_BLUE,       false,       &noVariable,             NONE,				        true,);


    //Shop Items                                                                                                                                                                                                                                     Repeatable				price
    itemTable[BUY_ARROWS_30]                     = Item(Text{"Buy Arrows (30)",                 "Acheter: Flèches (30)",            "Comprar flechas (30)"},                    ITEMTYPE_SHOP,  0x01,                 true,        &BuyArrow,               ARROWS_30,				    true,              60);
    itemTable[BUY_ARROWS_50]                     = Item(Text{"Buy Arrows (50)",                 "Acheter: Flèches (50)",            "Comprar flechas (50)"},                    ITEMTYPE_SHOP,  0x02,                 true,        &BuyArrow,               ARROWS_30,				    true,              90);
    itemTable[BUY_DEKU_NUT_10]                   = Item(Text{"Buy Deku Nut (10)",               "Acheter: Noix Mojo (10)",          "Comprar Nueces deku (10)"},                ITEMTYPE_SHOP,  0x04,                 true,        &Nuts,                   DEKU_NUTS_10,				true,              30);
    itemTable[BUY_DEKU_STICK_1]                  = Item(Text{"Buy Deku Stick (1)",              "Acheter: Bâton Mojo (1)",          "Comprar palos deku (1)"},                  ITEMTYPE_SHOP,  0x05,                 true,        &Sticks,                 DEKU_STICK_1,				true,              10);
    itemTable[BUY_BOMBS_10]                      = Item(Text{"Buy Bombs (10)",                  "Acheter: Bombes (10)",             "Comprar Bombas (10)"},                     ITEMTYPE_SHOP,  0x06,                 true,        &BuyBomb,                BOMBS_10,				    true,              50);
    itemTable[BUY_RED_POTION]                    = Item(Text{"Buy Red Potion ",                 "Acheter: Potion rouge ",           "Comprar poción roja "},                    ITEMTYPE_SHOP,  0x08,                 false,       &noVariable,             NONE,				        true,              30);
    itemTable[BUY_GREEN_POTION]                  = Item(Text{"Buy Green Potion",                "Acheter: Potion verte",            "Comprar poción verde"},                    ITEMTYPE_SHOP,  0x09,                 true,        &BuyGPotion,             NONE,				        true,              30);
    itemTable[BUY_BLUE_POTION]                   = Item(Text{"Buy Blue Potion",                 "Acheter: Potion bleue",            "Comprar poción azul"},                     ITEMTYPE_SHOP,  0x0A,                 true,        &BuyBPotion,             NONE,				        true,              100);
    itemTable[BUY_HEROS_SHIELD]                  = Item(Text{"Buy Hero's Shield",               "Acheter: Bouclier Hylien",         "Comprar escudo hyliano"},                  ITEMTYPE_SHOP,  0x0C,                 true,        &HerosShield,            HEROS_SHIELD,               true,              80);
    itemTable[BUY_BOMBCHU_10]                    = Item(Text{"Buy Bombchu (10)",                "Acheter: Bombchus (10)",           "Comprar bombchus (10)"},                   ITEMTYPE_SHOP,  0x15,                 true,        &BuyBombchus10,          BOMBCHU_10,				    true,              99);
    itemTable[SOLD_OUT]                          = Item(Text{"Sold Out",                        "Vendu",                            "Vendido"},                                 ITEMTYPE_SHOP,  0x26,                 false,       &noVariable,             NONE,				        true,              0);
    itemTable[BUY_FAIRYS_SPIRIT]                 = Item(Text{"Buy Fairy's Spirit",              "Acheter: Fée",                     "Comprar hada"},                            ITEMTYPE_SHOP,  0x2B,                 true,        &FairyAccess,            BOTTLE_WITH_FAIRY,			true,              50);

//    itemTable[TRIFORCE]                          = Item(Text{"Triforce",                        "Triforce",                         "Trifuerza"},                               ITEMTYPE_EVENT, GI_RUPEE_RED_LOSE,  false, &noVariable, NONE);
    itemTable[HINT]                              = Item(Text{"Hint",                            "Indice",                           "Pista"},                                   ITEMTYPE_EVENT, GI_RUPEE_BLUE_LOSE,   false,       &noVariable,             NONE				        true,);

}

Item& ItemTable(const ItemKey itemKey) {
    return itemTable[itemKey];
}

