#include "item_list.hpp"

#include "logic.hpp"
#include "../code/include/z3D/z3Ditem.h"
#include <array>

using namespace Logic;

static std::array<Item, KEY_ENUM_MAX> itemTable;

void ItemTable_Init() {                                   //English name     					French          					Spanish         							Item Type       getItemID    	advancement     logic       hint key			       //repeatable? true = yes false = no
    itemTable[NONE]                              = Item(Text{"No Item",                         "Rien",                             "Sin Objeto"},                              ITEMTYPE_EVENT, GI_RUPEE_GREEN,    false,    &noVariable,  NONE,						true);
    itemTable[KOKIRI_SWORD]                      = Item(Text{"Kokiri Sword",                    "Épée Kokiri",                      "Espada Kokiri"},                           ITEMTYPE_ITEM,  GI_SWORD_KOKIRI,   true,     &KokiriSword, KOKIRI_SWORD);
//	itemTable[RAZOR_SWORD]						 = Item(Text{"Razor Sword",						"Lame Rasoir",						"Espada Afilada"},							ITEMTYPE_ITEM,	GI_SWORD_RAZOR,	   false,	 &noVariable,	RAZOR_SWORD);
//    itemTable[GILDED_SWORD]                      = Item(Text{"Gilded Sword",                    "Lame Doree",                       "Espada de Esmeril"},                       ITEMTYPE_ITEM,  GI_SWORD_GILDED,   false,      &noVariable,    GILDED_SWORD);
    itemTable[GREAT_FAIRYS_SWORD]                = Item(Text{"Great Fairys Sword",              "Grande Épée de Fees",              "Espada de la Gran Hada"},                  ITEMTYPE_ITEM,  GI_SWORD_GFS,      true,       &noVariable,    GREAT_FAIRYS_SWORD,		false);
    itemTable[HEROS_SHIELD]                      = Item(Text{"Heros Shield",                    "Bouclier du Heros",                "Escudo del Heroe"},                        ITEMTYPE_ITEM,  GI_SHIELD_HERO,    false,      &noVariable,    HEROS_SHIELD,			true,);
    itemTable[MIRROR_SHIELD]                     = Item(Text{"Mirror Shield",                   "Bouclier miroir",                  "Escudo espejo"},                           ITEMTYPE_ITEM,  GI_SHIELD_MIRROR,  true,       &MirrorShield,  MIRROR_SHIELD,			false,);
    																																																			
	itemTable[LAND_TITLE]						 = Item(Text{"Land Title Deed",					"Titre de propriete fonciere",      "Escritura de propiedad de la Tierra",      ITEMTYPE_ITEM,  GI_LAND_TITLE,     true,       &LandTitle,     LAND_TITLE,				true,);
	itemTable[SWAMP_TITLE]						 = Item(Text{"Swamp Title Deed",				"Titre de propriete des marais",	"Escriture de propiedad del pantano",		ITEMTYPE_ITEM,  GI_SWAMP_TITLE,	   true,		&SwampTitle,   SWAMP_TITLE,				true,);
	itemTable[MOUNTAIN_TITLE]					 = Item(Text{"Mountain Title Deed",				"Titre de propriete de la montagne","Escitura de propiedad de la montana",		ITEMTYPE_ITEM,  GI_MOUNTAIN_TITLE, true,       &MountainTitle,  MOUNTAIN_TITLE,			true,);
	itemTable[OCEAN_TITLE]						 = Item(Text{"Ocean Title Deed",				"Titre de propriete de l'ocean",	"Escitura de propiedad del oceano",			ITEMTYPE_ITEM,  GI_OCEAN_TITLE,    true,       &OceanTitle,     OCEAN_TITLE,			true,);
	itemTable[BOMBERS_NOTEBOOK]					 = Item(Text{"Bomber's Notebook",				"Carnet de bombardier",				"Cuaderno de bombardero",					ITEMTYPE_ITEM,  GI_BOMBERS_NOTEBOOK, true,     &BombersNotebook, BOMBERS_NOTEBOOK,		false,);
	itemTable[ROOM_KEY]							 = Item(Text{"Room Key",						"Clef de chambre",					"Llave del cuarto",							ITEMTYPE_ITEM,  GI_ROOM_KEY,       true,       &RoomKey,      ROOM_KEY,					true,);
	itemTable[LETTER_KAFEI]						 = Item(Text{"Letter to Kafei",					"Lettre a Kafei",					"Carta a Kafei",							ITEMTYPE_ITEM,  GI_LETTER_KAFEI,   true,		&KafeiLetter,   LETTER_KAFEI,			true,);
	itemTable[PENDANT_MEMORIES]					 = Item(Text{"Pendant of Memories",				"Pendentif de Souvenirs",			"Colgante de recuerdos",					ITEMTYPE_ITEM,  GI_PENDANT_MEMORIES, true,     &PendantMemories,  PENDANT_MEMORIES,		true,);
	itemTable[LETTER_MAMA]						 = Item(Text{"Special Delivery to Mama",		"Livraison speciale a maman",		"Entrega especial a mama",					ITEMTYPE_ITEM,  GI_LETTER_MAMA,    true,		&LetterMama,    LETTER_MAMA,			true,);
	itemTable[MOONS_TEAR]						 = Item(Text{"Moon's Tear",						"Larme de lune",					"Lagrima de luna",							ITEMTYPE_ITEM,  GI_MOONS_TEAR,     true,        &MoonsTear,     MOONS_TEAR,				true,);
	itemTable[SPIN_ATTACK]						 = Item(Text{"Spin Attack",						"attaque de rotation",				"ataque giratorio",							ITEMTYPE_ITEM,	GI_SPIN_ATTACK,		true,		&SpinAttack,	SPIN_ATTACK,			false,);
//    itemTable[BOOMERANG]                         = Item(Text{"Boomerang",                       "Boomerang",                        "Búmeran"},                                 ITEMTYPE_ITEM,  GI_BOOMERANG,      true,       &Boomerang,     BOOMERANG);
    itemTable[LENS_OF_TRUTH]                     = Item(Text{"Lens of Truth",                   "Loupe de vérité",                  "Lupa de la Verdad"},                       ITEMTYPE_ITEM,  GI_LENS,           true,       &LensOfTruth,   LENS_OF_TRUTH,			false,);
    itemTable[FIRE_ARROWS]                       = Item(Text{"Fire Arrow",                      "Flèche de feu",                    "Flecha de fuego"},                         ITEMTYPE_ITEM,  GI_ARROW_FIRE,     true,       &FireArrows,    FIRE_ARROWS,				false,);
    itemTable[ICE_ARROWS]                        = Item(Text{"Ice Arrow",                       "Flèche de glace",                  "Flecha de hielo"},                         ITEMTYPE_ITEM,  GI_ARROW_ICE,      true,       &IceArrows,     ICE_ARROWS,				false,);
    itemTable[LIGHT_ARROWS]                      = Item(Text{"Light Arrow",                     "Flèche de lumière",                "Flecha de luz"},                           ITEMTYPE_ITEM,  GI_ARROW_LIGHT,    true,       &LightArrows,   LIGHT_ARROWS,			false,);
    itemTable[HOOKSHOT]							 = Item(Text{"Hookshot",						"Grappin",							"Gancho"									ITEMTYPE_ITEM,  GI_HOOKSHOT,	   true,	   &Hookshot,	   HOOKSHOT,				false,);
	itemTable[MAGIC_BEAN]                        = Item(Text{"Magic Bean",                      "Haricot magique",                  "Habichuelas mágicas"},                     ITEMTYPE_ITEM,  GI_BEAN,           true,       &MagicBean,     MAGIC_BEAN,				true,);
    itemTable[MAGIC_BEAN_PACK]                   = Item(Text{"Magic Bean Pack",                 "Paquet de haricots magiques",      "Lote de habichuelas mágicas"},             ITEMTYPE_ITEM,  0xC9,              true,       &MagicBeanPack, MAGIC_BEAN_PACK);
    itemTable[DOUBLE_DEFENSE]                    = Item(Text{"Double Defense",                  "Double défence",                   "Doble poder defensivo"},                   ITEMTYPE_ITEM,  0xB8,              true,       &noVariable,    DOUBLE_DEFENSE,			false,);
	itemTable[OCARINA_OF_TIME]                   = Item(Text{"Ocarina of Time",                 "Ocarina du temps",                 "Ocarina del Tiempo"},                      ITEMTYPE_ITEM, 	GI_OCARINA_OF_TIME,true,  	   &OcarinaOfTime, OCARINA_OF_TIME,			false,);
    itemTable[PICTOGRAPH_BOX]                    = Item(Text{"Pictograph Box",                  "Boite a Images",                   "Camara Pictografica"},                     ITEMTYPE_ITEM,  GI_PICTOGRAPH_BOX, true,       &PictographBox, PICTOGRAPH_BOX,			false,);
    itemTable[POWDER_KEG]                        = Item(Text{"Powder Keg",                      "Baril de Poudre",                  "Barril de Polovora"},                      ITEMTYPE_ITEM,  GI_POWDER_KEG,     true,       &PowderKeg,     POWDER_KEG,				true,);
//    itemTable[ZELDAS_LETTER]                     = Item(Text{"Zelda's Letter",                  "Lettre de Zelda",                  "Carta de Zelda"},                          ITEMTYPE_ITEM,  GI_LETTER_ZELDA,   true,       &ZeldasLetter,  ZELDAS_LETTER);
    itemTable[KEATON_MASK]                       = Item(Text{"Keaton Mask",                     "Masque de Keaton",                 "Careta de Keaton"},                        ITEMTYPE_ITEM,  GI_MASK_KEATON,    true,       &KeatonMask,    KEATON_MASK,				false,);
//  itemTable[SKULL_MASK]                        = Item(Text{"Skull Mask",                      "Masque de mort",                   "Máscara de calavera"},                     ITEMTYPE_ITEM,  GI_MASK_SKULL,     true,       &SkullMask,     SKULL_MASK);
//  itemTable[SPOOKY_MASK]                       = Item(Text{"Spooky Mask",                     "Masque d'Effroi",                  "Máscara tenebrosa"},                       ITEMTYPE_ITEM,  GI_MASK_SPOOKY,    true,       &SpookyMask,    SPOOKY_MASK);
    itemTable[BUNNY_HOOD]                        = Item(Text{"Bunny Hood",                      "Masque du lapin",                  "Capucha de conejo"},                       ITEMTYPE_ITEM,  GI_MASK_BUNNY,     true,       &BunnyHood,     BUNNY_HOOD,				false,);
    itemTable[GORON_MASK]                        = Item(Text{"Goron Mask",                      "Masque Goron",                     "Máscara Goron"},                           ITEMTYPE_ITEM,  GI_MASK_GORON,     true,       &GoronMask,     GORON_MASK,				false,);
    itemTable[ZORA_MASK]                         = Item(Text{"Zora Mask",                       "Masque Zora",                      "Máscara Zora"},                            ITEMTYPE_ITEM,  GI_MASK_ZORA,      true,       &ZoraMask,      ZORA_MASK,				false,);
    itemTable[DEKU_MASK]                         = Item(Text{"Deku Mask",                       "Masque Mojo",                      "Máscara Deku"},                            ITEMTYPE_ITEM,  GI_MASK_DEKU,      true,       &DekuMask,      DEKU_MASK,				false,);
    itemTable[POSTMANS_HAT]                      = Item(Text{"Postman's Mask",                  "Chapeau de facteur",               "Sombrero de cartero"},                     ITEMTYPE_ITEM,  GI_MASK_POSTMAN,   true,       &Postmanshat,   POSTMANS_HAT,				false,);
    itemTable[ALL_NIGHT_MASK]                    = Item(Text{"All-Night Mask",                  "Masque de nuit",                   "Máscara toda la noche"},                   ITEMTYPE_ITEM,  GI_MASK_ALL_NIGHT, true,       &AllNightMask,  ALL_NIGHT_MASK,				false,);
    itemTable[BLAST_MASK]                        = Item(Text{"Blast Mask",                      "Masque anti-explosion",            "Máscara explosiva"},                       ITEMTYPE_ITEM,  GI_MASK_BLAST,     true,       &BlastMask,     BLAST_MASK,				false,);
    itemTable[STONE_MASK]                        = Item(Text{"Stone Mask",                      "Masque de pierre",                 "Máscara de piedra"},                       ITEMTYPE_ITEM,  GI_MASK_STONE,     true,       &StoneMask,     STONE_MASK,				false,);
    itemTable[GREAT_FAIRYS_MASK]                 = Item(Text{"Great Fairy's Mask",              "Masque de grande fee",             "Máscara de gran hada"},                    ITEMTYPE_ITEM,  GI_MASK_GREAT_FAIRY, true,     &GreatFairyMask,GREAT_FAIRYS_MASK,				false,);
    itemTable[BREMEN_MASK]                       = Item(Text{"Bremen Mask",                     "Masque de Breme",                  "Máscara de Bremen"},                       ITEMTYPE_ITEM,  GI_MASK_BREMEN,    true,       &BremenMask,    BREMEN_MASK,				false,);
    itemTable[DON_GEROS_MASK]                    = Item(Text{"Don Gero's Mask",                 "Masque de Don Gero",               "Máscara de Don Gero"},                     ITEMTYPE_ITEM,  GI_MASK_DON_GERO,  true,       &DonGeroMask,   DON_GEROS_MASK,				false,);
    itemTable[MASK_OF_SCENTS]                    = Item(Text{"Mask of Scents",                  "Masque des Senteurs",              "Máscara de aromas"},                       ITEMTYPE_ITEM,  GI_MASK_SCENTS,    true,       &ScentsMask,    MASK_OF_SCENTS,				false,);
    itemTable[ROMANIS_MASK]                      = Item(Text{"Romani's Mask",                   "Masque de Romani",                 "Máscara de Romani"},                       ITEMTYPE_ITEM,  GI_MASK_ROMANI,    true,       &RomaniMask,    ROMANIS_MASK,				false,);
    itemTable[CIRCUS_LEADERS_MASK]               = Item(Text{"Circus Leader's Mask",            "Masque de chef de cirque",         "Máscara de lider de circo"},               ITEMTYPE_ITEM,  GI_MASK_CIRCUS,    true,       &CircusMask,    CIRCUS_LEADERS_MASK,				false,);
    itemTable[KAFEIS_MASK]                       = Item(Text{"Kafei's Mask",                    "Masque de Kafei",                  "Máscara de Kafei"},                        ITEMTYPE_ITEM,  GI_MASK_KAFEI,     true,       &KafeiMask,     KAFEIS_MASK,				false,);
    itemTable[COUPLES_MASK]                      = Item(Text{"Couple's Mask",                   "Masque de couple",                 "Máscara de pareja"},                       ITEMTYPE_ITEM,  GI_MASK_COUPLE,    true,       &CoupleMask,    COUPLES_MASK,				false,);
    itemTable[KAMAROS_MASK]                      = Item(Text{"Kamaro's Mask",                   "Masque de Kamaro",                 "Máscara de Kamaro"},                       ITEMTYPE_ITEM,  GI_MASK_KAMARO,    true,       &KamaroMask,    KAMAROS_MASK,				false,);
    itemTable[GIBDOS_MASK]                       = Item(Text{"Gibdo's Mask",                    "Masque Gibdo",                     "Máscara de Gibdo"},                        ITEMTYPE_ITEM,  GI_MASK_GIBDO,     true,       &GibdoMask,     GIBDOS_MASK,				false,);
    itemTable[GAROS_MASK]                        = Item(Text{"Garo's Mask",                     "Masque de Garo",                   "Máscara de Garo"},                         ITEMTYPE_ITEM,  GI_MASK_GARO,      true,       &GaroMask,      GAROS_MASK,				false,);
    itemTable[CAPTAINS_HAT]                      = Item(Text{"Captain's Hat",                   "Chapeau de capitaine",             "Sombrero de Capitan"},                     ITEMTYPE_ITEM,  GI_MASK_CAPTAIN,   true,       &CaptainHat,    CAPTAINS_HAT,				false,);
    itemTable[GIANTS_MASK]                       = Item(Text{"Giant's Mask",                    "Masque de geant",                  "Máscara de gigante"},                      ITEMTYPE_ITEM,  GI_MASK_GIANT,     true,       &GiantsMask,    GIANTS_MASK,				false,);
    itemTable[FIERCE_DIETY_MASK]                 = Item(Text{"Fierce Diety Mask",               "Masque Dietetique Fiere",          "Máscara Fiere Diety"},                     ITEMTYPE_ITEM,  GI_MASK_FIERCE,    true,       &FierceMask,    FIERCE_DIETY_MASK,				false,);
    itemTable[MASK_OF_TRUTH]                     = Item(Text{"Mask of Truth",                   "Masque de vérité",                 "Máscara de la Verdad"},                    ITEMTYPE_ITEM,  GI_MASK_MASK,      true,       &MaskofTruth,   MASK_OF_TRUTH,				false,);
//
    itemTable[SWAMP_SKULLTULA_TOKEN]             = Item(Text{"Swamp Skulltula Token",           "Jeton de Skulltula dorée",         "Símbolo de skulltula dorada"},             ITEMTYPE_SWAMP_TOKEN, GI_SWAMP_TOKEN,    true,       &SwampSkulltulaTokens, SWAMP_SKULLTULA_TOKEN,				false,);
	itemTable[OCEANSIDE_SKULLTULA_TOKEN]         = Item(Text{"Oceanside Skulltula Token",       "Jeton de Skulltula dorée",         "Símbolo de skulltula dorada"},             ITEMTYPE_OCEANSIDE_TOKEN, GI_OCEANSIDE_TOKEN,    true,       &OceansideSkulltulaTokens, OCEANSIDE_SKULLTULA_TOKEN,				false,);
	
	itemTable[CT_STRAY_FAIRY]					 = Item(Text{"Clock Town Stray Fairy",			"Fee errante de la Bourg-Clocher",	"Cuidad Reloj Hada Callejera"},				ITEMTYPE_ITEM,	GI_CT_SF,	true,		&ClockStray,	CT_STRAY_FAIRY,				false,);
	itemTable[WF_STRAY_FAIRY]					 = Item(Text{"Woodfall Stray Fairy",			"Fee errante de la Bois-Cascade",	"Hada Callejera del Bosque  Catarata"},		ITEMTYPE_ITEM,	GI_WF_SF,	true,	&WoodfallStrays,	WF_STRAY_FAIRY,				false,);
	itemTable[SH_STRAY_FAIRY]					 = Item(Text{"Snowhead Stray Fairy",			"Fee errante de la Pic des Neiges",	"Hada Callejera del Pico Nevado"},			ITEMTYPE_ITEM,	GI_SH_SF,	true,	&SnowheadStrays,	SH_STRAY_FAIRY,				false,);
	itemTable[GBT_STRAY_FAIRY]					 = Item(Text{"Great Bay Stray Fairy",			"Fee errante de la Grande Baie",	"Gran Hada Callejera de la Bahia"},			ITEMTYPE_ITEM,	GI_GBT_SF,	true,		&GreatBayStrays,	GBT_STRAY_FAIRY,				false,);
	itemTable[ST_STRAY_FAIRY]					 = Item(Text{"Stone Tower Stray Fairy",			"Fee errante de la Forteresse de Pierre",	"Hada Callejera de la Torre Piedra"},ITEMTYPE_ITEM,	GI_ST_SF,	true,		&StoneTowerStrays,	ST_STRAY_FAIRY,				false,);
		

    //Progression Items
	itemTable[PROGRESSIVE_SWORD]				 = Item(Text{"Progressive Sword",				"Lame (prog.)",						"Espada progresivo"							ITEMTYPE_ITEM,		0x80, true, &ProgressiveSword,		PROGRESSIVE_SWORD,				false,);
  //  itemTable[PROGRESSIVE_HOOKSHOT]              = Item(Text{"Progressive Hookshot",            "Grappin (prog.)",                  "Gancho progresivo"},                       ITEMTYPE_ITEM,     0x80, true,  &ProgressiveHookshot,  PROGRESSIVE_HOOKSHOT);
  //  itemTable[PROGRESSIVE_STRENGTH]              = Item(Text{"Progressive Strength Upgrade",    "Amélioration de force (prog.)",    "Fuerza progresiva"},                       ITEMTYPE_ITEM,     0x81, true,  &ProgressiveStrength,  PROGRESSIVE_STRENGTH);
    itemTable[PROGRESSIVE_BOMB_BAG]              = Item(Text{"Progressive Bomb Bag",            "Sac de bombes (prog.)",            "Saco de bombas progresivo"},               ITEMTYPE_ITEM,     0x82, true,  &ProgressiveBombBag,   PROGRESSIVE_BOMB_BAG,				false,);
    itemTable[PROGRESSIVE_BOW]                   = Item(Text{"Progressive Bow",                 "Arc (prog.)",                      "Arco progresivo"},                         ITEMTYPE_ITEM,     0x83, true,  &ProgressiveBow,       PROGRESSIVE_BOW,				false,);
  //  itemTable[PROGRESSIVE_SLINGSHOT]             = Item(Text{"Progressive Slingshot",           "Lance-pierre (prog.)",             "Resortera progresiva"},                    ITEMTYPE_ITEM,     0x84, true,  &ProgressiveBulletBag, PROGRESSIVE_SLINGSHOT);
    itemTable[PROGRESSIVE_WALLET]                = Item(Text{"Progressive Wallet",              "Bourse (prog.)",                   "Bolsa de rupias progresiva"},              ITEMTYPE_ITEM,     0x85, true,  &ProgressiveWallet,    PROGRESSIVE_WALLET,				false,);
  //  itemTable[PROGRESSIVE_SCALE]                 = Item(Text{"Progressive Scale",               "Écaille (prog.)",                  "Escama progresiva"},                       ITEMTYPE_ITEM,     0x86, true,  &ProgressiveScale,     PROGRESSIVE_SCALE);
  //  itemTable[PROGRESSIVE_NUT_UPGRADE]           = Item(Text{"Progressive Nut Capacity",        "Capacité de noix (prog.)",         "Capacidad de nueces deku progresiva"},     ITEMTYPE_ITEM,     0x87, false, &noVariable,           PROGRESSIVE_NUT_UPGRADE);
  //  itemTable[PROGRESSIVE_STICK_UPGRADE]         = Item(Text{"Progressive Stick Capacity",      "Capacité de bâtons (prog.)",       "Capacidad de palos deku progresiva"},      ITEMTYPE_ITEM,     0x88, false, &noVariable,           PROGRESSIVE_STICK_UPGRADE);
    itemTable[PROGRESSIVE_BOMBCHUS]              = Item(Text{"Progressive Bombchu",             "Bombchus (prog.)",                 "Bombchus progresivos"},                    ITEMTYPE_ITEM,     0x89, true,  &Bombchus,             PROGRESSIVE_BOMBCHUS,				false,);
    itemTable[PROGRESSIVE_MAGIC_METER]           = Item(Text{"Progressive Magic Meter",         "Jauge de magie (prog.)",           "Poder mágico progresivo"},                 ITEMTYPE_ITEM,     0x8A, true,  &ProgressiveMagic,     PROGRESSIVE_MAGIC_METER,				false,);
  //  itemTable[PROGRESSIVE_OCARINA]               = Item(Text{"Progressive Ocarina",             "Ocarina (prog.)",                  "Ocarina progresiva"},                      ITEMTYPE_ITEM,     0x8B, true,  &ProgressiveOcarina,   PROGRESSIVE_OCARINA);
  //  itemTable[PROGRESSIVE_GORONSWORD]            = Item(Text{"Progressive Goron Sword",         "Épée Goron (prog.)",               "Espada Goron progresiva"},                 ITEMTYPE_ITEM,     0xD4, true,  &noVariable,           PROGRESSIVE_GORONSWORD);

    //Bottles
    itemTable[EMPTY_BOTTLE]                      = Item(Text{"Empty Bottle",                    "Flacon vide",                      "Botella vacía"},                           ITEMTYPE_ITEM,     0x0F, true, &HasBottle, EMPTY_BOTTLE,				false,);
    itemTable[BOTTLE_WITH_MILK]                  = Item(Text{"Bottle with Milk",                "Flacon de lait",                   "Botella de leche Lon Lon"},                ITEMTYPE_ITEM,     0x14, true, &HasBottle, BOTTLE_WITH_MILK,				true,);
    itemTable[BOTTLE_WITH_RED_POTION]            = Item(Text{"Bottle with Red Potion",          "Flacon de potion rouge",           "Botella de poción roja"},                  ITEMTYPE_ITEM,     0x8C, true, &HasBottle, BOTTLE_WITH_RED_POTION,				true,);
    itemTable[BOTTLE_WITH_GREEN_POTION]          = Item(Text{"Bottle with Green Potion",        "Flacon de potion verte",           "Botella de poción verde"},                 ITEMTYPE_ITEM,     0x8D, true, &HasBottle, BOTTLE_WITH_GREEN_POTION,				true,);
    itemTable[BOTTLE_WITH_BLUE_POTION]           = Item(Text{"Bottle with Blue Potion",         "Flacon de potion bleue",           "Botella de poción azul"},                  ITEMTYPE_ITEM,     0x8E, true, &HasBottle, BOTTLE_WITH_BLUE_POTION,				true,);
    itemTable[BOTTLE_WITH_FAIRY]                 = Item(Text{"Bottle with Fairy",               "Flacon avec une fée",              "Hada en una botella"},                     ITEMTYPE_ITEM,     0x8F, true, &HasBottle, BOTTLE_WITH_FAIRY,				true,);
    itemTable[BOTTLE_WITH_FISH]                  = Item(Text{"Bottle with Fish",                "Flacon avec un poisson",           "Pez en una botella"},                      ITEMTYPE_ITEM,     0x90, true, &HasBottle, BOTTLE_WITH_FISH,				true,);
    itemTable[CHATEAU_ROMANI]        			 = Item(Text{"Chateau Romani",           		"Chateau Romani",          			"Reserva Romani"},                 			ITEMTYPE_ITEM,GI_CHATEAU, true, &HasBottle, CHATEAU_ROMANI,				true,);
    itemTable[BOTTLE_WITH_BUGS]                  = Item(Text{"Bottle with Bugs",                "Flacon d'insectes",                "Insecto en una botella"},                  ITEMTYPE_ITEM,     0x92, true, &HasBottle, BOTTLE_WITH_BUGS,				true,);
    itemTable[BOTTLE_WITH_POE]                   = Item(Text{"Bottle with Poe",                 "Flacon avec un Esprit",            "Poe en una botella"},                      ITEMTYPE_ITEM,     0x94, true, &HasBottle, BOTTLE_WITH_POE,				true,);
	itemTable[HOT_SPRING_WATER]                  = Item(Text{"Hot Spring Water",   			    "Eau de Source Chaude",       	    "Agua de Manantial Caliente"},              ITEMTYPE_ITEM,GI_HOT_SPRING_WATRE, true, &HotSpringWater,      HOT_SPRING_WATER,				true,);
    itemTable[SPRING_WATER]                      = Item(Text{"Spring Water",   			        "Eau de Pluie",       	            "Agua de Manantial"},                       ITEMTYPE_ITEM,GI_SPRING_WATER, true, &SpringWater,      SPRING_WATER,				true,);
    
    //Special bottles that can't immediately dump contents
    itemTable[DEKU_PRINCESS]                     = Item(Text{"Deku Princess",   			    "Princesse Mojo",       	        "Princesa Deku"},                           ITEMTYPE_ITEM,GI_PRINCESS, true, &DekuPrincess,      DEKU_PRINCESS,				true,);
    itemTable[BOTTLE_WITH_BIG_POE]               = Item(Text{"Bottle with Big Poe",             "Flacon avec une Âme",              "Gran Poe en una botella"},                 ITEMTYPE_ITEM,     0x93, true, &BottleWithBigPoe, BOTTLE_WITH_BIG_POE,				true,);
	itemTable[GOLD_DUST]  	                     = Item(Text{"Gold Dust",   			  	    "Poudre d'Or",       	      		"Polvo de Oro"},                            ITEMTYPE_ITEM,GI_GOLD_DUST, true, &GoldDust,      GOLD_DUST,				true,);
    itemTable[ZORA_EGG]							 = Item(Text{"Zora Egg", 						"Oeuf de Zora",						"Huevo de Zora"},							ITEMTYPE_ITEM, GI_ZORA_EGG, true, &ZoraEgg,			ZORA_EGG,				true,);
	itemTable[SEAHORSE]							 = Item(Text{"Seahorse",						"Hippocampe",						"Caballo de mar"},							ITEMTYPE_ITEM, GI_SEAHORSE, true, &Seahorse,	SEAHORSE,				true,);
	
    //Songs
    itemTable[SONG_OF_TIME]                      = Item(Text{"Song of Time",                    "Chant du temps",                   "Canción del tiempo"},                      ITEMTYPE_SONG,     0xC5, true, &SongOfTime,       SONG_OF_TIME,				false,);
    itemTable[SONG_OF_STORMS]                    = Item(Text{"Song of Storms",                  "Chant des tempêtes",               "Canción de la tormenta"},                  ITEMTYPE_SONG,     0xC6, true, &SongOfStorms,     SONG_OF_STORMS,				false,);
    itemTable[SONATA_OF_AWAKENING]               = Item(Text{"Sonata of Awakening",             "Sonate de i'Eveil",                "Sonata del Despertar"},                    ITEMTYPE_SONG,     0xBB, true, &SonataOfAwakening,SONATA_OF_AWAKENING,				false,);
    itemTable[GORONS_LULLABY]                    = Item(Text{"Goron's Lullaby",                 "Berceuse des Gorons",              "Nana Goron"},                       		ITEMTYPE_SONG,     0xBC, true, &GoronsLullaby,    GORONS_LULLABY,				false,);
    itemTable[NEW_WAVE_BOSSA_NOVA]               = Item(Text{"New Wave Bossa Nova",             "Bossa Nova des Flots",             "Nueva Bossanova"},                         ITEMTYPE_SONG,     0xBD, true, &NewWaveBossaNova,  NEW_WAVE_BOSSA_NOVA,				false,);
    itemTable[ELEGY_OF_EMPTINESS]                = Item(Text{"Elegy of Emptiness",              "Hymne du Vida",                    "Elegia al Vacio"},                         ITEMTYPE_SONG,     0xBE, true, &ElegyOfEmptiness,  ELEGY_OF_EMPTINESS,				false,);
    itemTable[OATH_TO_ORDER]               		 = Item(Text{"Oath to Order",             	    "Ode lAppel",       		        "Oda al Order"},   			                ITEMTYPE_SONG,     0xBF, true, &OathToOrder, 		OATH_TO_ORDER,				false,);
    itemTable[EPONAS_SONG]                       = Item(Text{"Epona's Song",                    "Chant d'Épona",                    "Canción de Epona"},                        ITEMTYPE_SONG,     0xC1, true, &EponasSong,       EPONAS_SONG,				false,);
    itemTable[INVERTED_SONG_OF_TIME]             = Item(Text{"Inverted Song of Time",           "Chant du Temps Inverse",           "Canción del Tiempo Invertida"},            ITEMTYPE_SONG,     0xC2, true, &InvertedSongOfTime,   INVERTED_SONG_OF_TIME,				false,);
    itemTable[SONG_OF_DOUBLE_TIME]               = Item(Text{"Song of Double Time",             "Chant du Temps Accelere",          "Canción del Doble Tiempo"},                ITEMTYPE_SONG,     0xC3, true, &SongOfDoubleTime,     SONG_OF_DOUBLE_TIME,				false,);
    itemTable[SONG_OF_HEALING]                   = Item(Text{"Song of Healing",                 "Chant de l'Apaisement",            "Sonata de Curacion"},                      ITEMTYPE_SONG,     0xC4, true, &SongOfHealing,         SONG_OF_HEALING,				false,);
    itemTable[SONG_OF_SOARING]                   = Item(Text{"Song of Soaring",                 "Chant de l'Envol",                 "Canción de Vuelo"},                        ITEMTYPE_SONG,     0xC0, true, &SongOfSoaring,         SONG_OF_SOARING,				false,);
    
    //Maps and Compasses
    itemTable[WOODFALL_TEMPLE_MAP]               = Item(Text{"Woodfall Temple Map",             "Carte de Temple de Bois-Cascade",  "Mapa del Templo del Bosque Catarata"},     ITEMTYPE_MAP,      0xA5, false, &noVariable, MAP,				false,);
    itemTable[SNOWHEAD_TEMPLE_MAP]               = Item(Text{"Snowhead Temple Map",             "Carte de Temple du Pic des Neiges","Mapa del Templo del Pico Nevado"},         ITEMTYPE_MAP,      0xA6, false, &noVariable, MAP,				false,);
    itemTable[GBT_MAP]              = Item(Text{"Great Bay Temple Map",            "Carte de Temple de la Grande Baie","Mapa del Templo de la Gran Bahia"},        ITEMTYPE_MAP,      0xA7, false, &noVariable, MAP,				false,);
    itemTable[STONE_TOWER_TEMPLE_MAP]            = Item(Text{"Stone Tower Temple Map",          "Carte du Temple de la Forteresse de Pierre","Mapa del Templo de la Torre de Piedra"},ITEMTYPE_MAP,0xA8, false, &noVariable, MAP,				false,);
    itemTable[CLOCK_TOWN_MAP]                    = Item(Text{"Clock Town Map",                  "Carte de Bourg-Clocher",           "Mapa de la Cuidad Reloj"},                 ITEMTYPE_MAP,      0xA9, false, &noVariable, MAP,				false,);
    itemTable[WOODFALL_MAP]                      = Item(Text{"Woodfall Map",                    "Carte du Bois-Cascade",            "Mapa del Bosque Catarata"},                ITEMTYPE_MAP,      0xAA, false, &noVariable, MAP,				false,);
    itemTable[SNOWHEAD_MAP]                      = Item(Text{"Snowhead Map",                    "Carte du Pic Des Neiges",          "Mapa del Pico Nevado"},                    ITEMTYPE_MAP,      0xAB, false, &noVariable, MAP,				false,);
    itemTable[GREAT_BAY_MAP]                     = Item(Text{"Great Bay Map",                   "Carte du Plage de la Grande Baie", "Mapa del Costa de la Gran Bahia"},         ITEMTYPE_MAP,      0xAC, false, &noVariable, MAP,				false,);
    itemTable[STONE_TOWER_MAP]                   = Item(Text{"Stone Tower Map",                 "Carte du Forteresse de Pierre",    "Mapa del Torre de Piedra"},                ITEMTYPE_MAP,      0xAD, false, &noVariable, MAP,				false,);
    itemTable[ROMANI_RANCH_MAP]                  = Item(Text{"Romani Ranch Map",                "Carte de Ranch Romani",            "Mapa de Rancho Romani"},                   ITEMTYPE_MAP,      0xAE, false, &noVariable, MAP,				false,);

    itemTable[WOODFALL_TEMPLE_COMPASS]           = Item(Text{"Woodfall Temple Compass",         "Boussole de Temple de Bois-Cascade", "Brújula del Templo del Bosque Catarata"},             ITEMTYPE_COMPASS,  0x9B, false, &noVariable, COMPASS,				false,);
    itemTable[SNOWHEAD_TEMPLE_COMPASS]           = Item(Text{"Snowhead Temple Compass",         "Boussole de Temple du Pic des Neiges","Brújula del Templo del Pico Nevado"},     ITEMTYPE_COMPASS,  0x9C, false, &noVariable, COMPASS,				false,);
    itemTable[GBT_COMPASS]          = Item(Text{"Great Bay Temple Compass",        "Boussole de Temple de la Grande Baie","Brújula del Templo de la Gran Bahia"},        ITEMTYPE_COMPASS,  0x9D, false, &noVariable, COMPASS,				false,);
    itemTable[STONE_TOWER_TEMPLE_COMPASS]             = Item(Text{"Stone Tower Temple Compass", "Boussole du Teple de la Forteresse de Pierre", "Brújula del Templo de la Torre de Piedra"},           ITEMTYPE_COMPASS,  0x9E, false, &noVariable, COMPASS,				false,);
//    itemTable[FIRE_TEMPLE_COMPASS]               = Item(Text{"Fire Temple Compass",             "Boussole du temple du feu",        "Brújula del Templo del Fuego"},            ITEMTYPE_COMPASS,  0x9F, false, &noVariable, COMPASS);
//    itemTable[WATER_TEMPLE_COMPASS]              = Item(Text{"Water Temple Compass",            "Boussole du temple de l'eau",      "Brújula del Templo del Agua"},             ITEMTYPE_COMPASS,  0xA0, false, &noVariable, COMPASS);
//    itemTable[SPIRIT_TEMPLE_COMPASS]             = Item(Text{"Spirit Temple Compass",           "Boussole du temple de l'esprit",   "Brújula del Templo del Espíritu"},         ITEMTYPE_COMPASS,  0xA1, false, &noVariable, COMPASS);
//    itemTable[SHADOW_TEMPLE_COMPASS]             = Item(Text{"Shadow Temple Compass",           "Boussole du temple de l'ombre",    "Brújula del Templo de las Sombras"},       ITEMTYPE_COMPASS,  0xA2, false, &noVariable, COMPASS);
//    itemTable[BOTTOM_OF_THE_WELL_COMPASS]        = Item(Text{"Bottom of the Well Compass",      "Boussole du fond du puits",        "Brújula del fondo del pozo"},              ITEMTYPE_COMPASS,  0xA3, false, &noVariable, COMPASS);
//    itemTable[ICE_CAVERN_COMPASS]                = Item(Text{"Ice Cavern Compass",              "Boussole de la caverne polaire",   "Brújula de la caverna de hielo"},          ITEMTYPE_COMPASS,  0xA4, false, &noVariable, COMPASS);

    //Boss Keys
    itemTable[WOODFALL_TEMPLE_BOSS_KEY]          = Item(Text{"Woodfall Temple Big Key",         "Clé d'or du Temple de Bois-Cascade",   "Gran llave del Templo del Bosque Catarata"},        ITEMTYPE_BOSSKEY,  0x95, true, &BossKeyWoodfallTemple, BOSS_KEY,				true,);
    itemTable[SNOWHEAD_TEMPLE_BOSS_KEY]          = Item(Text{"Snowhead Temple Big Key",         "Clé d'or du Temple du Pic des Neiges",        "Gran llave del Templo del Pico Nevado"},         ITEMTYPE_BOSSKEY,  0x96, true, &BossKeySnowheadTemple,   BOSS_KEY,				true,);
    itemTable[GBT_BOSS_KEY]         = Item(Text{"Great Bay Temple Big Key",        "Clé d'or du Temple de la Grande Baie",      "Gran llave del Templo de la Gran Bahia"},          ITEMTYPE_BOSSKEY,  0x97, true, &BossKeyGreatBayTemple,  BOSS_KEY,				true,);
    itemTable[STONE_TOWER_TEMPLE_BOSS_KEY]       = Item(Text{"Stone Tower Temple Big Key",      "Clé d'or du Temple de la Forteresse de Pierre",   "Gran llave del Templo de la Torre de Piedra"},      ITEMTYPE_BOSSKEY,  0x98, true, &BossKeyStoneTowerTemple, BOSS_KEY,				true,);
//    itemTable[SHADOW_TEMPLE_BOSS_KEY]            = Item(Text{"Shadow Temple Big Key",           "Clé d'or du temple de l'ombre",    "Gran llave del Templo de las Sombras"},    ITEMTYPE_BOSSKEY,  0x99, true, &BossKeyShadowTemple, BOSS_KEY);
//    itemTable[GANONS_CASTLE_BOSS_KEY]            = Item(Text{"Ganon's Castle Big Key",          "Clé d'or du château de Ganon",     "Gran llave del Castillo de Ganon"},        ITEMTYPE_BOSSKEY,  0x9A, true, &BossKeyGanonsCastle, GANONS_CASTLE_BOSS_KEY);

    //Small Keys
    itemTable[WOODFALL_TEMPLE_SMALL_KEY]         = Item(Text{"Woodfall Temple Small Key",       "Petite clé du Temple de Bois-Cascade", "Llave del Templo del Templo del Bosque Catarata"},             ITEMTYPE_SMALLKEY,          0xAF, true, &WoodfallTempleKeys,          SMALL_KEY,				true,);
    itemTable[SNOWHEAD_TEMPLE_SMALL_KEY]         = Item(Text{"Snowhead Temple Small Key",       "Petite clé du Temple du Pic des Neiges",      "Llave del Templo del Pico Nevado"},              ITEMTYPE_SMALLKEY,          0xB0, true, &SnowheadTempleKeys,            SMALL_KEY,				true,);
    itemTable[GBT_SMALL_KEY]        = Item(Text{"Great Bay Temple Small Key",      "Petite clé du Temple de la Grande Baie",    "Llave del Templo del la Gran Bahia"},               ITEMTYPE_SMALLKEY,          0xB1, true, &GreatBayTempleKeys,           SMALL_KEY,				true,);
    itemTable[STONE_TOWER_TEMPLE_SMALL_KEY]      = Item(Text{"Stone Tower Temple Small Key",    "Petite clé du Temple de la Forteresse de Pierre", "Llave del Templo de la Torre de Piedra"},           ITEMTYPE_SMALLKEY,          0xB2, true, &StoneTowerTempleKeys,          SMALL_KEY,				true,);
//    itemTable[SHADOW_TEMPLE_SMALL_KEY]           = Item(Text{"Shadow Temple Small Key",         "Petite clé du temple de l'ombre",  "Llave del Templo de las Sombras"},         ITEMTYPE_SMALLKEY,          0xB3, true, &ShadowTempleKeys,          SMALL_KEY);
//    itemTable[BOTTOM_OF_THE_WELL_SMALL_KEY]      = Item(Text{"Bottom of the Well Small Key",    "Petite clé du fond du puits",      "Llave del fondo del pozo"},                ITEMTYPE_SMALLKEY,          0xB4, true, &BottomOfTheWellKeys,       SMALL_KEY);
//    itemTable[GERUDO_TRAINING_GROUNDS_SMALL_KEY] = Item(Text{"Training Grounds Small Key",      "Petite clé du gymnase Gerudo",     "Llave del Centro de Instrucción"},         ITEMTYPE_SMALLKEY,          0xB5, true, &GerudoTrainingGroundsKeys, SMALL_KEY);
//    itemTable[GERUDO_FORTRESS_SMALL_KEY]         = Item(Text{"Gerudo Fortress Small Key",       "Petite clé du repaire Gerudo",     "Llave de la Fortaleza Gerudo"},            ITEMTYPE_FORTRESS_SMALLKEY, 0xB6, true, &GerudoFortressKeys,        GERUDO_FORTRESS_SMALL_KEY);
//    itemTable[GANONS_CASTLE_SMALL_KEY]           = Item(Text{"Ganon's Castle Small Key",        "Petite clé du château de Ganon",   "Llave del Castillo de Ganon"},             ITEMTYPE_SMALLKEY,          0xB7, true, &GanonsCastleKeys,          SMALL_KEY);

    //Stones and Medallions
    itemTable[ODOLWAS_REMAINS]                   = Item(Text{"Odolwa's Remains",                "Restes d'Odolwa",                  "Restos de Odolwa"},                        ITEMTYPE_DUNGEONREWARD, 0xCB,  true, &OdolwasRemains,   ODOLWAS_REMAINS,				false,);
    itemTable[GOHTS_REMAINS]                     = Item(Text{"Goht's Remains",                  "Restes de Rohrk",                  "Restos de Goht"},                          ITEMTYPE_DUNGEONREWARD, 0xCC,  true, &GohtsRemains,     GOHTS_REMAINS,				false,);
    itemTable[GYORGS_REMAINS]                    = Item(Text{"Gyorg's Remains",                 "Restes de Gyorg",                  "Restos de Gyorg"},                         ITEMTYPE_DUNGEONREWARD, 0xCD,  true, &GyorgsRemains,    GYORGS_REMAINS,				false,);
    itemTable[TWINMOLDS_REMAINS]                 = Item(Text{"Twinmold's Remains",              "Restes de Skorn",                  "Restos dde Twinmod"},                      ITEMTYPE_DUNGEONREWARD, 0xCE,  true, &TwinmoldsRemains, TWINMOLDS_REMAINS,				false,);
//    itemTable[FIRE_MEDALLION]                    = Item(Text{"Fire Medallion",                  "Médaillon du feu",                 "Medallón del Fuego"},                      ITEMTYPE_DUNGEONREWARD, 0xCF,  true, &FireMedallion,   FIRE_MEDALLION);
//    itemTable[WATER_MEDALLION]                   = Item(Text{"Water Medallion",                 "Médaillon de l'eau",               "Medallón del Agua"},                       ITEMTYPE_DUNGEONREWARD, 0xD0,  true, &WaterMedallion,  WATER_MEDALLION);
//    itemTable[SPIRIT_MEDALLION]                  = Item(Text{"Spirit Medallion",                "Médaillon de l'esprit",            "Medallón del Espíritu"},                   ITEMTYPE_DUNGEONREWARD, 0xD1,  true, &SpiritMedallion, SPIRIT_MEDALLION);
//    itemTable[SHADOW_MEDALLION]                  = Item(Text{"Shadow Medallion",                "Médaillon de l'ombre",             "Medallón de la Sombra"},                   ITEMTYPE_DUNGEONREWARD, 0xD2,  true, &ShadowMedallion, SHADOW_MEDALLION);
//    itemTable[LIGHT_MEDALLION]                   = Item(Text{"Light Medallion",                 "Médaillon de la lumière",          "Medallón de la Luz"},                      ITEMTYPE_DUNGEONREWARD, 0xD3,  true, &LightMedallion,  LIGHT_MEDALLION);

    //Generic Items
    itemTable[RECOVERY_HEART]                    = Item(Text{"Recovery Heart",                  "Cœur d'énergie",                   "Corazón"},                                 ITEMTYPE_ITEM, GI_HEART,             false, &noVariable, RECOVERY_HEART,				true,);
    itemTable[GREEN_RUPEE]                       = Item(Text{"Green Rupee",                     "Rubis vert",                       "Rupia verde"},                             ITEMTYPE_ITEM, GI_RUPEE_GREEN,       false, &noVariable, GREEN_RUPEE,				true,);
    itemTable[BLUE_RUPEE]                        = Item(Text{"Blue Rupee",                      "Rubis bleu",                       "Rupia azul"},                              ITEMTYPE_ITEM, GI_RUPEE_BLUE,        false, &noVariable, BLUE_RUPEE,				true,);
    itemTable[RED_RUPEE]                         = Item(Text{"Red Rupee",                       "Rubis rouge",                      "Rupia roja"},                              ITEMTYPE_ITEM, GI_RUPEE_RED,         false, &noVariable, RED_RUPEE,				true,);
    itemTable[PURPLE_RUPEE]                      = Item(Text{"Purple Rupee",                    "Rubis pourpre",                    "Rupia morada"},                            ITEMTYPE_ITEM, GI_RUPEE_PURPLE,      false, &noVariable, PURPLE_RUPEE,				true,);
    itemTable[HUGE_RUPEE]                        = Item(Text{"Huge Rupee",                      "Énorme rubis",                     "Rupia gigante"},                           ITEMTYPE_ITEM, GI_RUPEE_GOLD,        false, &noVariable, HUGE_RUPEE,				true,);
    itemTable[SILVER_RUPEE]                      = Item(Text{"Silver Rupee",                    "rubis d'argent",                   "Rupia de plata"},                          ITEMTYPE_ITEM, GI_RUPEE_SILVER,      false, &noVariable, SILVER_RUPEE,				true,);
    itemTable[PIECE_OF_HEART]                    = Item(Text{"Piece of Heart",                  "Quart de cœur",                    "Pieza de corazón"},                        ITEMTYPE_ITEM, GI_HEART_PIECE,       false, &noVariable, PIECE_OF_HEART,				false,);
    itemTable[HEART_CONTAINER]                   = Item(Text{"Heart Container",                 "Réceptacle de cœur",               "Contenedor de corazón"},                   ITEMTYPE_ITEM, GI_HEART_CONTAINER_2, false, &noVariable, HEART_CONTAINER,				false);
    itemTable[ICE_TRAP]                          = Item(Text{"Ice Trap",                        "Piège de glace",                   "Trampa de hielo"},                         ITEMTYPE_ITEM, GI_ICE_TRAP,          false, &noVariable, ICE_TRAP,				true,);
    itemTable[MILK]                              = Item(Text{"Milk",                            "Lait",                             "Leche Lon Lon"},                           ITEMTYPE_ITEM, GI_MILK,              false, &noVariable, NONE,				true,);

    //Refills
    itemTable[BOMBS_5]                           = Item(Text{"Bombs (5)",                       "Bombes (5)",                       "Bombas (5)"},                              ITEMTYPE_REFILL, GI_BOMBS_5,        false, &noVariable,  BOMBS_5,				true,);
    itemTable[BOMBS_10]                          = Item(Text{"Bombs (10)",                      "Bombes (10)",                      "Bombas (10)"},                             ITEMTYPE_REFILL, GI_BOMBS_10,       false, &noVariable,  BOMBS_10,				true,);
    itemTable[BOMBS_20]                          = Item(Text{"Bombs (20)",                      "Bombes (20)",                      "Bombas (20)"},                             ITEMTYPE_REFILL, GI_BOMBS_20,       false, &noVariable,  BOMBS_20,				true,);
    itemTable[BOMBCHU_5]                         = Item(Text{"Bombchu (5)",                     "Bombchus (5)",                     "Bombchus (5)"},                            ITEMTYPE_REFILL, GI_BOMBCHUS_5,     true,  &Bombchus5,   BOMBCHU_5,				true,);
    itemTable[BOMBCHU_10]                        = Item(Text{"Bombchu (10)",                    "Bombchus (10)",                    "Bombchus (10)"},                           ITEMTYPE_REFILL, GI_BOMBCHUS_10,    true,  &Bombchus10,  BOMBCHU_10,				true,);
    itemTable[BOMBCHU_20]                        = Item(Text{"Bombchu (20)",                    "Bombchus (20)",                    "Bombchus (20)"},                           ITEMTYPE_REFILL, GI_BOMBCHUS_20,    true,  &Bombchus20,  BOMBCHU_20,				true,);
    itemTable[BOMBCHU_DROP]                      = Item(Text{"Bombchu Drop",                    "Bombchus",                         "Bombchus"},                                ITEMTYPE_DROP,   GI_BOMBCHUS_10,    true,  &BombchuDrop, NONE,				true,);
    itemTable[ARROWS_5]                          = Item(Text{"Arrows (5)",                      "Flèches (5)",                      "Flechas (5)"},                             ITEMTYPE_REFILL, GI_ARROWS_SMALL,   false, &noVariable,  ARROWS_5,				true,);
    itemTable[ARROWS_10]                         = Item(Text{"Arrows (10)",                     "Flèches (10)",                     "Flechas (10)"},                            ITEMTYPE_REFILL, GI_ARROWS_MEDIUM,  false, &noVariable,  ARROWS_10,				true,);
    itemTable[ARROWS_30]                         = Item(Text{"Arrows (30)",                     "Flèches (30)",                     "Flechas (30)"},                            ITEMTYPE_REFILL, GI_ARROWS_LARGE,   false, &noVariable,  ARROWS_30,				true,);
    itemTable[DEKU_NUTS_5]                       = Item(Text{"Deku Nuts (5)",                   "Noix Mojo (5)",                    "Nueces deku (5)"},                         ITEMTYPE_REFILL, GI_NUTS_5,         false, &noVariable,  DEKU_NUTS_5,				true,);
    itemTable[DEKU_NUTS_10]                      = Item(Text{"Deku Nuts (10)",                  "Noix Mojo (10)",                   "Nueces deku (10)"},                        ITEMTYPE_REFILL, GI_NUTS_10,        false, &noVariable,  DEKU_NUTS_10,				true,);
    //itemTable[DEKU_SEEDS_30]                     = Item(Text{"Deku Seeds (30)",                 "Graines Mojo (30)",                "Semillas deku (30)"},                      ITEMTYPE_REFILL, GI_SEEDS_30,       false, &noVariable,  DEKU_SEEDS_30,				true,);
    //itemTable[DEKU_STICK_1]                      = Item(Text{"Deku Stick (1)",                  "Bâton Mojo (1)",                   "Palo deku (1)"},                           ITEMTYPE_REFILL, GI_STICKS_1,       false, &noVariable,  DEKU_STICK_1,				true,);
    itemTable[RED_POTION_REFILL]                 = Item(Text{"Red Potion Refill",               "Potion rouge",                     "Recarga de poción roja"},                  ITEMTYPE_REFILL, GI_POTION_RED,     false, &noVariable,  NONE,				true,);
    itemTable[GREEN_POTION_REFILL]               = Item(Text{"Green Potion Refill",             "Potion verte",                     "Recarga de poción verde"},                 ITEMTYPE_REFILL, GI_POTION_GREEN,   false, &noVariable,  NONE,				true,);
    itemTable[BLUE_POTION_REFILL]                = Item(Text{"Blue Potion Refill",              "Potion bleue",                     "Recarga de poción azul"},                  ITEMTYPE_REFILL, GI_POTION_BLUE,    false, &noVariable,  NONE,				true,);

    //Treasure Game
//    itemTable[TREASURE_GAME_HEART]               = Item(Text{"Piece of Heart (Treasure Chest Minigame)",    "Quart de cœur (Chasse-aux-trésors)",   "Pieza de corazón (Cofre del Tesoro)"},     ITEMTYPE_ITEM, GI_HEART_PIECE_WIN,  false, &noVariable, TREASURE_GAME_HEART);
//    itemTable[TREASURE_GAME_GREEN_RUPEE]         = Item(Text{"Green Rupee (Treasure Chest Minigame)",       "Rubis vert (Chasse-aux-trésors)",      "Rupia Verde (Cofre del Tesoro)"},          ITEMTYPE_ITEM, GI_RUPEE_GREEN_LOSE, false, &noVariable, TREASURE_GAME_GREEN_RUPEE);

    //Shop Items                                                                                                                                                                                                                                     Repeatable				price
//    itemTable[BUY_DEKU_NUT_5]                    = Item(Text{"Buy Deku Nut (5)",                "Acheter: Noix Mojo (5)",           "Comprar nueces deku (5)"},                 ITEMTYPE_SHOP, 0x00, true,  &Nuts,           DEKU_NUTS_5,				true,            15);
    itemTable[BUY_ARROWS_30]                     = Item(Text{"Buy Arrows (30)",                 "Acheter: Flèches (30)",            "Comprar flechas (30)"},                    ITEMTYPE_SHOP, 0x01, true,  &BuyArrow,       ARROWS_30,				true,              60);
    itemTable[BUY_ARROWS_50]                     = Item(Text{"Buy Arrows (50)",                 "Acheter: Flèches (50)",            "Comprar flechas (50)"},                    ITEMTYPE_SHOP, 0x02, true,  &BuyArrow,       ARROWS_30,				true,              90);
//    itemTable[BUY_BOMBS_525]                     = Item(Text{"Buy Bombs (5) [25]",              "Acheter: Bombes (5) [25]",         "Comprar bombas (5) [25]"},                 ITEMTYPE_SHOP, 0x03, true,  &BuyBomb,        BOMBS_5,				true,                25);
    itemTable[BUY_DEKU_NUT_10]                   = Item(Text{"Buy Deku Nut (10)",               "Acheter: Noix Mojo (10)",          "Comprar Nueces deku (10)"},                ITEMTYPE_SHOP, 0x04, true,  &Nuts,           DEKU_NUTS_10,				true,           30);
    itemTable[BUY_DEKU_STICK_1]                  = Item(Text{"Buy Deku Stick (1)",              "Acheter: Bâton Mojo (1)",          "Comprar palos deku (1)"},                  ITEMTYPE_SHOP, 0x05, true,  &Sticks,         DEKU_STICK_1,				true,           10);
    itemTable[BUY_BOMBS_10]                      = Item(Text{"Buy Bombs (10)",                  "Acheter: Bombes (10)",             "Comprar Bombas (10)"},                     ITEMTYPE_SHOP, 0x06, true,  &BuyBomb,        BOMBS_10,				true,               50);
//    itemTable[BUY_FISH]                          = Item(Text{"Buy Fish",                        "Acheter: Poisson",                 "Comprar pez"},                             ITEMTYPE_SHOP, 0x07, true,  &FishAccess,     BOTTLE_WITH_FISH,				true,      200);
    itemTable[BUY_RED_POTION_30]                 = Item(Text{"Buy Red Potion [30]",             "Acheter: Potion rouge [30]",       "Comprar poción roja [30]"},                ITEMTYPE_SHOP, 0x08, false, &noVariable,     NONE,				true,                   30);
    itemTable[BUY_GREEN_POTION]                  = Item(Text{"Buy Green Potion",                "Acheter: Potion verte",            "Comprar poción verde"},                    ITEMTYPE_SHOP, 0x09, true,  &BuyGPotion,     NONE,				true,                   30);
    itemTable[BUY_BLUE_POTION]                   = Item(Text{"Buy Blue Potion",                 "Acheter: Potion bleue",            "Comprar poción azul"},                     ITEMTYPE_SHOP, 0x0A, true,  &BuyBPotion,     NONE,				true,                  100);
    itemTable[BUY_HEROS_SHIELD]                  = Item(Text{"Buy Hero's Shield",               "Acheter: Bouclier Hylien",         "Comprar escudo hyliano"},                  ITEMTYPE_SHOP, 0x0C, true,  &HerosShield,   HEROS_SHIELD,          80);
//    itemTable[BUY_DEKU_SHIELD]                   = Item(Text{"Buy Deku Shield",                 "Acheter: Bouclier Mojo",           "Comprar escudo deku"},                     ITEMTYPE_SHOP, 0x0D, true,  &DekuShield,     DEKU_SHIELD,            40);
//    itemTable[BUY_GORON_TUNIC]                   = Item(Text{"Buy Goron Tunic",                 "Acheter: Tunique Goron",           "Comprar sayo goron"},                      ITEMTYPE_SHOP, 0x0E, true,  &GoronTunic,     GORON_TUNIC,           200);
//    itemTable[BUY_ZORA_TUNIC]                    = Item(Text{"Buy Zora Tunic",                  "Acheter: Tunique Zora",            "Comprar sayo zora"},                       ITEMTYPE_SHOP, 0x0F, true,  &ZoraTunic,      ZORA_TUNIC,            300);
//    itemTable[BUY_HEART]                         = Item(Text{"Buy Heart",                       "Acheter: Coeur d'énergie",         "Comprar corazón"},                         ITEMTYPE_SHOP, 0x10, false, &noVariable,     RECOVERY_HEART,				true,         10);
    itemTable[BUY_BOMBCHU_10]                    = Item(Text{"Buy Bombchu (10)",                "Acheter: Bombchus (10)",           "Comprar bombchus (10)"},                   ITEMTYPE_SHOP, 0x15, true,  &BuyBombchus10,  BOMBCHU_10,				true,             99);
//    itemTable[BUY_BOMBCHU_20]                    = Item(Text{"Buy Bombchu (20)",                "Acheter: Bombchus (20)",           "Comprar bombchus (20)"},                   ITEMTYPE_SHOP, 0x16, true,  &BuyBombchus20,  BOMBCHU_20,				true,            180);
//    itemTable[BUY_BOMBCHU_5]                     = Item(Text{"Buy Bombchu (5)",                 "Acheter: Bombchus (5)",            "Comprar bombchus (5)"},                    ITEMTYPE_SHOP, 0x18, true,  &BuyBombchus5,   BOMBCHU_5,				true,              60);
    //itemTable[BUY_DEKU_SEEDS_30]                 = Item(Text{"Buy Deku Seeds (30)",             "Acheter: Graines Mojo (30)",       "Comprar semillas deku (30)"},              ITEMTYPE_SHOP, 0x1D, true,  &BuySeed,        DEKU_SEEDS_30,				true,          30);
    itemTable[SOLD_OUT]                          = Item(Text{"Sold Out",                        "Vendu",                            "Vendido"},                                 ITEMTYPE_SHOP, 0x26, false, &noVariable,     NONE,				true,                    0);
//    itemTable[BUY_BLUE_FIRE]                     = Item(Text{"Buy Blue Fire",                   "Acheter: Flamme bleue",            "Comprar fuego azul"},                      ITEMTYPE_SHOP, 0x27, true,  &BlueFireAccess, BOTTLE_WITH_BLUE_FIRE, 300);
//    itemTable[BUY_BOTTLE_BUG]                    = Item(Text{"Buy Bottle Bug",                  "Acheter: Insectes en flacon",      "Comprar bichos"},                          ITEMTYPE_SHOP, 0x28, true,  &BugsAccess,     BOTTLE_WITH_BUGS,				true,       50);
//    itemTable[BUY_POE]                           = Item(Text{"Buy Poe",                         "Acheter: Esprit",                  "Comprar Poe"},                             ITEMTYPE_SHOP, 0x2A, false, &noVariable,     BOTTLE_WITH_BIG_POE,				true,    30);
    itemTable[BUY_FAIRYS_SPIRIT]                 = Item(Text{"Buy Fairy's Spirit",              "Acheter: Fée",                     "Comprar hada"},                            ITEMTYPE_SHOP, 0x2B, true,  &FairyAccess,    BOTTLE_WITH_FAIRY,				true,      50);
//    itemTable[BUY_ARROWS_10]                     = Item(Text{"Buy Arrows (10)",                 "Acheter: Flèches (10)",            "Comprar flechas (10)"},                    ITEMTYPE_SHOP, 0x2C, true,  &BuyArrow,       ARROWS_10,				true,              20);
//    itemTable[BUY_BOMBS_20]                      = Item(Text{"Buy Bombs (20)",                  "Acheter: Flèches (20)",            "Comprar bombas (20)"},                     ITEMTYPE_SHOP, 0x2D, true,  &BuyBomb,        BOMBS_20,				true,               80);
//    itemTable[BUY_BOMBS_30]                      = Item(Text{"Buy Bombs (30)",                  "Acheter: Flèches (30)",            "Comprar bombas (30)"},                     ITEMTYPE_SHOP, 0x2E, true,  &BuyBomb,        BOMBS_20,				true,              120);
//    itemTable[BUY_BOMBS_535]                     = Item(Text{"Buy Bombs (5) [35]",              "Acheter: Bombes (5) [35]",         "Comprar bombas (5) [35]"},                 ITEMTYPE_SHOP, 0x2F, true,  &BuyBomb,        BOMBS_5,				true,                35);
    itemTable[BUY_RED_POTION_40]                 = Item(Text{"Buy Red Potion [40]",             "Acheter: Potion rouge [40]",       "Comprar poción roja [40]"},                ITEMTYPE_SHOP, 0x30, false, &noVariable,     NONE,				true,                   40);
    itemTable[BUY_RED_POTION_50]                 = Item(Text{"Buy Red Potion [50]",             "Acheter: Potion rouge [50]",       "Comprar poción roja [50]"},                ITEMTYPE_SHOP, 0x31, false, &noVariable,     NONE,				true,                   50);

//    itemTable[TRIFORCE]                          = Item(Text{"Triforce",                        "Triforce",                         "Trifuerza"},                               ITEMTYPE_EVENT, GI_RUPEE_RED_LOSE,  false, &noVariable, NONE);
    itemTable[HINT]                              = Item(Text{"Hint",                            "Indice",                           "Pista"},                                   ITEMTYPE_EVENT, GI_RUPEE_BLUE_LOSE, false, &noVariable, NONE				true,);

//  itemTable[HOOKSHOT]                          = Item(Text{"Hookshot",                        "Grappin",                          "Gancho"},                                  ITEMTYPE_ITEM, 0x80, true,  &ProgressiveHookshot, HOOKSHOT);
//  itemTable[LONGSHOT]                          = Item(Text{"Longshot",                        "Super-Grappin",                    "Supergancho"},                             ITEMTYPE_ITEM, 0x80, true,  &ProgressiveHookshot, LONGSHOT);
//  itemTable[FAIRY_OCARINA]                     = Item(Text{"Fairy Ocarina",                   "Ocarina des fées",                 "Ocarina de las Hadas"},                    ITEMTYPE_ITEM, 0x8B, true,  &ProgressiveOcarina, FAIRY_OCARINA);
//  itemTable[BOMB_BAG]                          = Item(Text{"Bomb Bag",                        "Sac de bombes",                    "Saco de bombas"},                          ITEMTYPE_ITEM, 0x82, true,  &ProgressiveBombBag, BOMB_BAG);
//  itemTable[BIG_BOMB_BAG]                      = Item(Text{"Big Bomb Bag",                    "Grand sac de bombes",              "Saco de bombas grande"},                   ITEMTYPE_ITEM, 0x82, true,  &ProgressiveBombBag, BIG_BOMB_BAG);
//  itemTable[BIGGEST_BOMB_BAG]                  = Item(Text{"Biggest Bomb Bag",                "Énorme sac de bombes",             "Saco de bombas gigante"},                  ITEMTYPE_ITEM, 0x82, true,  &ProgressiveBombBag, BIGGEST_BOMB_BAG);
//  itemTable[FAIRY_BOW]                         = Item(Text{"Fairy Bow",                       "Arc des fées",                     "Arco de las Hadas"},                       ITEMTYPE_ITEM, 0x83, true,  &ProgressiveBow, FAIRY_BOW);
//  itemTable[BIG_QUIVER]                        = Item(Text{"Big Quiver",                      "Grand carquois",                   "Carcaj grande"},                           ITEMTYPE_ITEM, 0x83, true,  &ProgressiveBow, BIG_QUIVER);
//  itemTable[BIGGEST_QUIVER]                    = Item(Text{"Biggest Quiver",                  "Énorme carquois",                  "Carcaj gigante"},                          ITEMTYPE_ITEM, 0x83, true,  &ProgressiveBow, BIGGEST_QUIVER);
//  itemTable[FAIRY_SLINGSHOT]                   = Item(Text{"Fairy Slingshot",                 "Lance-pierre des fées",            "Resortera de las hadas"},                  ITEMTYPE_ITEM, 0x84, true,  &ProgressiveBulletBag, FAIRY_SLINGSHOT);
//  itemTable[BIG_BULLET_BAG]                    = Item(Text{"Big Deku Seed Bullet Bag",        "Grand sac de graines mojo",        "Bolsa de semillas deku grande"},           ITEMTYPE_ITEM, 0x84, true,  &ProgressiveBulletBag, BIG_BULLET_BAG);
//  itemTable[BIGGEST_BULLET_BAD]                = Item(Text{"Biggest Deku Seed Bullet Bag",    "Énorme sac de graines mojo",       "Bolsa de semillas deku gigante"},          ITEMTYPE_ITEM, 0x84, true,  &ProgressiveBulletBag, BIGGEST_BULLET_BAD);
//  itemTable[GORONS_BRACELET]                   = Item(Text{"Goron's Bracelet",                "Bracelet Goron",                   "Brazalete de los Goron"},                  ITEMTYPE_ITEM, 0x81, true,  &ProgressiveStrength, GORONS_BRACELET);
//  itemTable[SILVER_GAUNTLETS]                  = Item(Text{"Silver Gauntlets",                "Gantelets d'argent",               "Guantes de plata"},                        ITEMTYPE_ITEM, 0x81, true,  &ProgressiveStrength, SILVER_GAUNTLETS);
//  itemTable[GOLDEN_GAUNTLETS]                  = Item(Text{"Golden Gauntlets",                "Gantelets d'or",                   "Guantes de oro"},                          ITEMTYPE_ITEM, 0x81, true,  &ProgressiveStrength, GOLDEN_GAUNTLETS);
//  itemTable[SILVER_SCALE]                      = Item(Text{"Silver Scale",                    "Écaille d'argent",                 "Escama de Plata"},                         ITEMTYPE_ITEM, 0x86, true,  &ProgressiveScale, SILVER_SCALE);
//  itemTable[GOLDEN_SCALE]                      = Item(Text{"Golden Scale",                    "Écaille d'or",                     "Escama de Oro"},                           ITEMTYPE_ITEM, 0x86, true,  &ProgressiveScale, GOLDEN_SCALE);
//  itemTable[ADULT_WALLET]                      = Item(Text{"Adult Wallet",                    "Bourse d'adulte",                  "Bolsa de adulto"},                         ITEMTYPE_ITEM, 0x85, true,  &ProgressiveWallet, ADULT_WALLET);
//  itemTable[GIANT_WALLET]                      = Item(Text{"Giant Wallet",                    "Bourse de géant",                  "Bolsa gigante"},                           ITEMTYPE_ITEM, 0x85, true,  &ProgressiveWallet, GIANT_WALLET);
//  itemTable[TYCOON_WALLET]                     = Item(Text{"Tycoon Wallet",                   "Bourse de star",                   "Bolsa de ricachón"},                       ITEMTYPE_ITEM, 0x85, true,  &ProgressiveWallet, TYCOON_WALLET);
//  itemTable[DEKU_NUT_CAPACITY_30]              = Item(Text{"Deku Nut Capacity (30)",          "Capacité de noix Mojo (20)",       "Capacidad de nueces deku (40)"},           ITEMTYPE_ITEM, 0x87, false, &noVariable, DEKU_NUT_CAPACITY_30);
//  itemTable[DEKU_NUT_CAPACITY_40]              = Item(Text{"Deku Nut Capacity (40)",          "Capacité de noix Mojo (30)",       "Capacidad de nueces deku (50)"},           ITEMTYPE_ITEM, 0x87, false, &noVariable, DEKU_NUT_CAPACITY_40);
//  itemTable[DEKU_NUT_CAPACITY_20]              = Item(Text{"Deku Stick Capacity (20)",        "Capacité de bâtons Mojo (20)",     "Capacidad de palos deku (20)"},            ITEMTYPE_ITEM, 0x88, false, &noVariable, DEKU_NUT_CAPACITY_20);
//  itemTable[DEKU_NUT_CAPACITY_30]              = Item(Text{"Deku Nut Capacity (30)",          "Capacité de noix Mojo (20)",       "Capacidad de nueces deku (40)"},           ITEMTYPE_ITEM, 0x88, false, &noVariable, DEKU_NUT_CAPACITY_30);
//  itemTable[MAGIC_METER]                       = Item(Text{"Magic Meter",                     "Jauge de magie",                   "Poder mágico"},                            ITEMTYPE_ITEM, 0x8A, true,  &ProgressiveMagic, MAGIC_METER);
//  itemTable[ENHANCED_MAGIC_METER]              = Item(Text{"Enhanced Magic Meter",            "Jauge de magie améliorée",         "Poder mágico mejorado"},                   ITEMTYPE_ITEM, 0x8A, true,  &ProgressiveMagic, ENHANCED_MAGIC_METER);

}

Item& ItemTable(const ItemKey itemKey) {
    return itemTable[itemKey];
}

//This function should only be used to place items containing hint text
//at gossip stone locations.
void NewItem(const ItemKey itemKey, const Item item) {
    if (itemKey <= BUY_RED_POTION_50) {
      printf("\x1b[25;0HWARNING: ATTEMPTED TO OVERWRITE ITEM %lu\n", itemKey);
      return;
    }

    itemTable[itemKey] = item;
}
